cloudformation/watched-account.template.yaml
hq/app/utils/attempt/Failure.scala

Update to the watched-account template to solve AWSSupport access denied issue:
```
security-hq is not authorized to perform: support: (Service: AWSSupport...
```
> To use the Trusted Advisor-related actions provided by the AWS Support API, your policy must include the support:* action (explicitly or implicitly); none of the trustedadvisor action permissions restrict your access.
http://docs.aws.amazon.com/IAM/latest/UserGuide/list_trustedadvisor.html

Add the support actions required for Trusted Advisor

---

build.sbt
cloudformation/security-hq.template.yaml
hq/app/AppComponents.scala
hq/app/auth/SecurityHQAuthActions.scala
hq/app/config/Config.scala
hq/app/controllers/AuthController.scala
hq/app/controllers/HQController.scala
hq/app/controllers/SecurityGroupsController.scala
hq/app/views/loginError.scala.html
hq/beanstalk/setup.sh
hq/conf/application.conf
hq/conf/routes

- New routes for login and login failure! 🎉
- Uses [play-googleauth](https://github.com/guardian/play-googleauth) to control access! 🎉
play-googleauth 0.6.0 has an issue with the cats that was currently in the project:
```
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn] 	* org.typelevel:cats-core_2.11:0.8.1 -> 1.0.0-MF
```
So it has been swapped out..

Add Google authentication to Security HQ

---

hq/app/aws/support/TrustedAdvisor.scala
hq/app/aws/support/TrustedAdvisorExposedIAMKeys.scala
hq/app/aws/support/TrustedAdvisorRDSSGs.scala
hq/app/aws/support/TrustedAdvisorSGOpenPorts.scala
hq/test/aws/support/TrustedAdvisorExposedIAMKeysTest.scala
hq/test/aws/support/TrustedAdvisorRDSSGsTest.scala
hq/test/aws/support/TrustedAdvisorSGOpenPortsTest.scala
hq/test/utils/attempt/AttemptValues.scala

Trusted Advisor was failing if the `SGIds` did not contain a `vpcId`, this adds a new case to handle `EC2 classic`, and updates the tests to include one for this issue.
This also moves away from using `throw new RuntimeException` when attempting to parse the metadata from Trusted Advisor

Resolve the unexpected errors when parsing SG open ports

---

hq/app/aws/ec2/EC2.scala
hq/test/aws/ec2/EC2Test.scala

Now puts accounts with the highest number of flagged resources first.

Reverse sort for accounts with flagged resources

---

.sass-lint.yml
hq/app/views/fragments/openSecurityGroups.scala.html
hq/app/views/sgs/sgs.scala.html
hq/public/javascripts/app.js
hq/public/stylesheets/main.css

Some changes for the Security Groups page! 
If there are multiple flagged resources they now appear in a dropdown that will open and close on hover:
The latest iteration is using numbers and icons on the dropdown. However, is still very much a hack / WIP.
There is still an issue where hovering and clicking will invert the behaviour... (not desirable)
Security groups now wrap to 1, 2 or 3 columns depending on the width of the viewport
The CSS breakpoints are lovingly taken [from frontend](https://github.com/guardian/frontend/blob/8fc430776d9992afab47429db9e45826e57a5c6f/static/src/stylesheets/_vars.scss#L51)
Long security group names should now wrap rather than overflow
Rows should all be the minimum hight required to accommodate their tallest card
Greedy containers let the security groups …

Style Security Groups, move flagged resources to dropdowns, and add sass-lint

---

hq/app/views/iam/iam.scala.html
hq/app/views/index.scala.html
hq/app/views/sgs/sgs.scala.html
hq/public/stylesheets/main.css

We need more visual cues that expandable menus are clickable, so first step is to add an icon:
- Less flex, more CSS grid
- Less CSS overall 🎉 🔥
- Deleting some html since the elements are no longer needed

Switch to CSS grid, and add icons to expandables

---

.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE.md

Adds a PR template and contributing guidelines inspired by (and adapted from) [Guardian frontend](https://github.com/guardian/frontend)
https://github.com/guardian/frontend/tree/master/.github
- Providing guidance on contributing
- Making me write less boilerplate with each PR
Nope!

Add initial PR template and contributing guidelines

---

hq/app/views/doc.scala.html
hq/app/views/fragments/openSecurityGroups.scala.html
hq/app/views/header.scala.html
hq/app/views/main.scala.html
hq/public/javascripts/app.js
hq/public/stylesheets/main.css

- Consistent design, header and headings taking less vertical space
- Making documentation discoverable by linking to it in the header
- Making documentation discoverable by linking to it in the footer
- Improving visual display at various breakpoints

Give Documentation page the new nav, add links to the docs in header and footer

---

.github/CONTRIBUTING.md

Contributor docs now mention that Riff Raff will auto-deploy successful builds.
Docs FTW

Updated CONTRIBUTING.md to reflect continuous deployment

---

.github/PULL_REQUEST_TEMPLATE.md
cloudformation/watched-account.template.yaml
hq/app/aws/AwsAsyncHandler.scala

- Adds required EC2 permission to the CloudFormation template
- Reduces specificity of matching on AWS error
- Adds question about CloudFormation to PR template
- Links PR template to the contributing guidelines
Template is under source control and can be used to update the StackSet
AWS seems to swap between using "you are" and "is" when reporting authorisation errors, so this PR makes the matching less specific to handle the different subjects
This is a good place to add a check and reminder about CloudFormation and StackSetting
Update to the CloudFormation template included since this is necessary if we are going to apply the changes from #34 
❗❗ The updated template will need to be applied to the watched-account StackSet. We can revert #47 once this has been done.

Update CloudFormation template and ask about CloudFormation in PR template

---

build.sbt

Upgrade AWS SDK version to 1.11.258
Stops the Credentials report breaking if it encounters `eu-west-3`
Nope

Upgrade AWS SDK version to latest release: 1.11.258

---

build.sbt
hq/app/AppComponents.scala
hq/app/controllers/SecurityGroupsController.scala
hq/app/services/CacheService.scala
hq/app/views/sgs/sgs.scala.html

Adds caching to the Security Groups
The service now stores the AWS response on flagged security groups into a [Box](https://github.com/guardian/box) 📦
Every 5 minutes, the service will refresh the Box content
The application can get the data from the Box, rather than running off to AWS each time. 
Speeds up the page load for the all accounts security groups page, and for the single account pages
No long trips over the wire delaying page load of the Security Groups 🏃💨
Nope

Add a cache service and integrate it with Security Groups

---

hq/app/AppComponents.scala
hq/app/aws/support/TrustedAdvisorExposedIAMKeys.scala
hq/app/controllers/HQController.scala
hq/app/services/CacheService.scala
hq/app/utils/attempt/Failure.scala

Adding methods to help get exposed keys for all accounts
Stores the AWS responses for Credentials and Exposed Keys into two separate [Boxes](https://github.com/guardian/box) 📦 📦
Adds a new Failure that can be reused across the cache service:
Speeds up the page load for the IAM pages
Adding the startingCache to each Box means no more blank pages while waiting for each service to start:
Nope
Related PR: #53

Expand the cache service to include Exposed Keys and Credentials Report

---

hq/app/views/header.scala.html
hq/public/stylesheets/main.css

Fixes issue where security groups dropdowns were overlaying mobile nav
Corrects the mobile nav link to the documentation
Bug fixes 🐞 
Nope
Nope

Fix z-index ordering and fix mobile nav link

---

hq/app/controllers/HQController.scala
hq/app/utils/attempt/Failure.scala
hq/app/views/iam/exposedKeys.scala.html
hq/app/views/iam/iamAccount.scala.html
hq/app/views/iam/iamCredReportBody.scala.html

This PR allows the IAM account pages on Security HQ to show a warning if either the credentials or exposed keys results in a failed attempt, while still showing the other report it that succeeds. 
For example, if the Exposed Keys cache service does not start, or fails to fetch data from AWS, the error makes it to the dashboard along with the available data (credentials report):
Worst case scenario, the user gets two bright error messages:
- Making a new fragment since the pattern matching adds noise
- Deleting some extra rows from the templates, and fixing indents to match other pages
Nope
Tested with demo exposed keys, hence the template changes to make the page layouts more consistent and aesthetically pleasing 💅

Let the reports for exposed keys and credentials fail/success independently

---

hq/markdown/run-command.md
ssm-util.sh

Saving everyone a few clicks
I think this order makes it easier to follow along and learn as you go. I ran through the guide and had some questions, so adding some verbosity for any AWS/EC2 beginners.
Script was not working as expected but was giving the helpful error:
```
Invalid choice: 'get-command-invocation', maybe you meant:
* list-command-invocations
```
The docs can link out to the example, and this will make it easier for others to copy the content
No visible change to web view. Some markdown viewers require this to format correctly.
Nope

Expansion of the EC2 run readme, and addition of an example shell script

---

cloudformation/watched-account.template.yaml
hq/app/aws/ec2/EC2.scala
hq/app/aws/support/TrustedAdvisor.scala
hq/app/aws/support/TrustedAdvisorSGOpenPorts.scala
hq/app/controllers/SecurityGroupsController.scala
hq/app/services/CacheService.scala

Currently the CacheService runs `refreshSgsBox()` every 5 minutes. This adds a step ( `EC2.refreshSGSReports` ) to that `refreshSgsBox()` by which we instruct AWS to update/refresh its security group open ports report. 
Increase the correctness (up-to-date-ness if I may) of the cache.
Yes. watched-account.template.yaml has been update to allow Trusted Advisor to run `Refresh`.

A Better Security Groups Cache Refresh

---

cloudformation/security-hq.template.yaml

Adds a `Name` tag to Security HQ instances
`Name` is a "convention" tag in AWS and is prominently displayed in the EC2 console. This will make it easy to identity Security HQ's instances(s) at a glance.
No.
This is a CloudFormation change for the application itself so we will need to manually update the CF stack in the AWS console.

Add name tag to Security HQ instances

---

build.sbt
cloudformation/security-hq.template.yaml
hq/app/AppComponents.scala
hq/app/api/Snyk.scala
hq/app/controllers/SnykController.scala
hq/app/logic/SnykDisplay.scala
hq/app/model/Serializers.scala
hq/app/model/models.scala
hq/app/views/header.scala.html
hq/app/views/index.scala.html
hq/app/views/main.scala.html
hq/app/views/snyk/snyk.scala.html
hq/conf/application.conf
hq/conf/routes
hq/markdown/index.md
hq/markdown/parameter-store.md
hq/markdown/snyk.md
hq/markdown/temporary-ssh.md
hq/public/javascripts/app.js
hq/public/javascripts/jquery.filtertable.js
hq/test/logic/SnykDisplayTest.scala
hq/test/utils/attempt/AttemptValues.scala
package.json

Adds a Snyk Report page
Fetches some configuration via Configraun configuration engine
Exposes the results of snyk testing for vulnerabilities, including vulnerabilities found after the 
initial test.
Configraun use removes a 'secret' from the configuration file and stores it in AWS Parameter Store.
We should be moving towards this approach generally.  This implementation provides a dogfood implementation for others to use.
Yes.
Template changes are included.
No

Add Snyk report and Configraun

---

hq/app/aws/ec2/EC2.scala
hq/app/controllers/HQController.scala
hq/app/logic/ReportDisplay.scala
hq/app/model/models.scala
hq/app/views/iam/iam.scala.html
hq/app/views/iam/iamCredReportBody.scala.html
hq/test/logic/ReportDisplayTest.scala

The all accounts IAM credentials report is currently sorted according to the account name...
This PR will make SHQ order the the accounts by the severity and number of alerts:
```
```
Users were once listed in alphabetical order, now the ones with severe alerts will appear at the top of their section! \* 
Metrics and motivation
Nope
The IAM body template currently builds from two distinct lists (humanUsers and machineUsers). Some refactoring of how the users are stored and the table is generated will be required before they can be sorted _together_
These changes only apply to the All Accounts page, since this is a good place to get an overview of how things are doing; I have left the original sorting in place on the individual account pages.

Sorting for the credentials reports, and the account names

---

hq/app/logic/ReportDisplay.scala
hq/app/model/models.scala
hq/app/views/fragments/allKeyStatus.scala.html
hq/app/views/fragments/credentialsHelp.scala.html
hq/app/views/fragments/humanReportStatus.scala.html
hq/app/views/fragments/machineReportStatus.scala.html
hq/app/views/fragments/username.scala.html
hq/app/views/iam/iam.scala.html
hq/app/views/iam/iamAccount.scala.html
hq/app/views/iam/iamCredReportBody.scala.html
hq/public/javascripts/app.js
hq/public/stylesheets/main.css

- Icon to indicate the inferred use type (human/machine)
- Help icon after the alert warning, to trigger display of the help modal
Appears on the all accounts and individual accounts pages and can be slightly different depending on the user type. Also contains some information about how user types are inferred.
- deleting small template fragment and moving lines to main template
- deleting unused css, and reordering css slightly
- removing unused data attributes from the html
- tweaks wording of the no active access key warning
Providing more information and support when SHQ users are looking at the IAM credentials report
Nope 
Wording and content of the modals can be iterated upon. 😄 
Flagging inactive users is a helpful way of encouraging old credentials to be deleted. I have …

User icons and helper modals for the IAM credentials reports

---

hq/app/logic/SecurityGroupDisplay.scala
hq/app/views/fragments/openSecurityGroups.scala.html
hq/app/views/sgs/sgs.scala.html
hq/app/views/sgs/sgsAccount.scala.html
hq/public/javascripts/app.js
hq/public/stylesheets/main.css
hq/test/logic/SecurityGroupDisplayTest.scala

Currently SHQ is not using the `isSuppressed` value from the TrustedAdvisor (TA) result.  If a Security Group warning is excluded/suppressed via the TA console `isSuppressed` will be `true`
> isSuppressed specifies whether the AWS resource was ignored by Trusted Advisor because it was marked as suppressed by the user.
This is a MVP at adding some filtering and visual cues to accommodate `isSuppressed`
- Add icon and tooltip to the card title
- Make the card background grey
- Add optional badges to show the number of excluded/suppressed Security Groups (SGs)
- Adds **permanent** card panel, with explainer text and checkboxes to toggle which SGs to display
- Defaults to showing flagged SGs with the ignored SGs hidden
- Adds **conditional** card panel about ignored Security Groups (SGs) …

Support for filtering suppressed SGs, add filter options to views

---

hq/app/views/iam/iam.scala.html
hq/app/views/sgs/sgs.scala.html

- Slightly improved accessibility since tab no longer ignores the accordions
- Users of [Vimium](https://vimium.github.io/) can enjoy greater keyboard control and navigation (Vimium is awesome - I recommend checking trying it out)
- Fewer clicks to navigate between all accounts and a specific individual account
Accessibility of JavaScript widgets ([MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/Keyboard-navigable_JavaScript_widgets))
Improved developer experience 🎁 
Nope
Nope

Make the accordions keyboard-navigable, add shortcut to account page

---

build.sbt
project/plugins.sbt

Removes the unnecessary import of sbt-native-packager version 1.3.2.

Removing unnecessary sbt pluging

---

cloudformation/security-hq.template.yaml
hq/upstart/security-hq.conf

Allows for two instances (minimum) up to four during deployments.
Adds a flag to collate memory usage in the JRE
To mitigate and investigate the instance failure due to memory exhaustion.
Yes
These changes can be reverted once the memory issues are understood and resolved.

Scale out and debug memory usage

---

hq/app/model/Serializers.scala
hq/app/model/models.scala
hq/test/logic/SnykDisplayTest.scala

Correct Snyk response information by deduplicating.
Some Issues are found through multiple dependency routes.  They should still, ideally, be
only counted as one.
No.
No.

Use Set for Snyk issues

---

hq/app/logic/SnykDisplay.scala
hq/app/views/doc.scala.html
hq/app/views/documentation/unknown.scala.html
hq/app/views/iam/iam.scala.html
hq/app/views/sgs/sgs.scala.html
hq/app/views/snyk/snyk.scala.html
hq/markdown/index.md
hq/public/javascripts/jquery.filtertable.js
hq/public/stylesheets/main.css

- Customise the heading font-sizes on the documentation pages, and use flow-text to auto-scale
- Update the Snyk report page to use the current sub header design
- Style the Snyk report search form and add clear button for filter
- Move some logic out of the templates
- Delete unused data attributes
- Updates to styling, and usage of icons and hyperlinks
- Consistent design
- Optimising readability
- Code maintenance 
Nope

Various styling and template improvements, and optimise readability of docs pages

---

cloudformation/security-hq.template.yaml
hq/conf/riff-raff.yaml

This change updates the `hq/conf/riff-raff.yaml` file to make it possible for Riff-Raff to use the latest available AMI of the `security-hq` AMIgo recipe.
This recipe puts `aws-tools`, `java8` and `ssm-agent` onto `ubuntu-trusty`.
Accordingly, `cloudformation/security-hq.template.yaml` has been updated  by removing the duplicate work. 
Note: Ideally we would not have `apt-get -y update` and `apt-get -y upgrade` running as part of the launch config, but this is not the concern of this PR. This problem, namely the fact that a backed AMI needs this, will be addressed separately. 
Note: Since the cloud formation file is picked up as part of the deployment, there is here no requirement to do it manually beforehand in AWS console.

Moving to AMIgo backed AMIs

---

build.sbt
package.json
sbt

Correct path for sbt executable (local wrapper script for Security HQ)
Adds command alias required by Snyk for sbt 1.0+
Turns off colour on sbt.
Upversions vulnerable library.
As is, Snyk fails to (1) find sbt; (2) invoke dependencyTree, (3) parse coloured output: this change corrects each of those so that Snyk tests can run.  
SHQ then did not pass the test; the upversioned library corrects this.
No
No

Correct path to sbt on team city

---

sbt

Removes the TC switch now that builds succeed without it.
Cleanliness.
No
No.

Deprecate Team City specific switch

---

hq/app/logic/ReportDisplay.scala
hq/app/logic/SecurityGroupDisplay.scala
hq/app/views/fragments/openSecurityGroups.scala.html
hq/app/views/fragments/securityGroupHelp.scala.html
hq/app/views/iam/iam.scala.html
hq/app/views/sgs/sgs.scala.html
hq/app/views/sgs/sgsAccount.scala.html
hq/public/javascripts/app.js
hq/public/stylesheets/main.css
hq/test/logic/ReportDisplayTest.scala

- Splitting flagged SGs into two subsets and giving separate counts for both
- Start laying down the rules and recommendations for SG issues
- Helper menu with expand all, collapse all options
- Adding inactive user count and icon to the expandable headings
- Fix overflow issue on docs page by adding correct classes
- HTML structure consistency
- using helper classes to size text
Supporting work for making SHQ more opinionated. 
Metrics are useful.
Nope

Expand all for IAM page MVP help modal for Security Groups pages, more scores 

---

hq/app/controllers/HQController.scala
hq/app/controllers/SecurityGroupsController.scala
hq/app/logic/ReportDisplay.scala
hq/app/views/fragments/mfa.scala.html
hq/app/views/fragments/warningMessage.scala.html
hq/app/views/iam/exposedKeys.scala.html
hq/app/views/iam/iam.scala.html
hq/app/views/iam/iamAccount.scala.html
hq/app/views/iam/iamCredReportBody.scala.html
hq/app/views/sgs/sgsAccount.scala.html
hq/public/stylesheets/main.css
hq/test/logic/ReportDisplayTest.scala

This is nicer and more unambiguous than the previously empty container. Teams should be pleased with their big green check! 👍 👍 
This significantly changes the page for an accounts security groups. Previously if the data was not available in the cache, the user would hit the standard error page. However, passing the error to the view allows some bonus styling, and keeps the user on their account hub, so they can still use the tabs on the sub nav.
We currently only show exposed keys on the individual account pages, which makes the warnings less likely to be encountered if someone is using the all accounts page. This PR adds a check for any accounts with exposed keys, and will add a red alert to the top of the page for each account. The alert links to the IAM account page which will have …

Display more helpful warnings, and confirm when there are no open security groups

---

build.sbt
cloudformation/watched-account.template.yaml
hq/app/aws/iam/CloudFormation.scala
hq/app/aws/iam/CredentialsReport.scala
hq/app/aws/iam/IAMClient.scala
hq/app/logic/ReportDisplay.scala
hq/app/model/models.scala
hq/app/views/fragments/allKeyStatus.scala.html
hq/app/views/iam/iamCredReportBody.scala.html
hq/test/aws/iam/CredentialsReportTest.scala
hq/test/logic/ReportDisplayTest.scala

Adds a cloud icon next to the user type to indicate if the user is associated with a CloudFormation stack. IAM user arns that do not match any stack output will have a cloud with a line through:
For IAM users that do have an associated CloudFormation stack, the stack name will appear on hover (as a tooltip) and the icon will be a link to the stack in the AWS console:
Simple identification of IAM users that have custom permissions/have not been Cloudformed
Yes - StackSet update TODO!
Currently, this is only checking in the default region for Stacks. The next step is to check across regions...

Add indication of related CloudFormation stack to IAM users

---

cloudformation/watched-account.template.yaml

Allows Security HQ to `describe-regions` that a watched account has available, which is useful if you need to iterate over regions at some point to discover what stacks are in each one **
** The enum of Regions available from the AWS SDK is not hugely helpful for this, since it contains ALL regions, including ones that an account may not be able to access. This is annoying if you are trying to `describe-stacks` without dealing with constant API errors 😣
Security HQ will be able to learn of all the stacks in a watched account, which is very useful if you want to cross-reference with IAM users to see which originate from CloudFormation
Putting changes into VC before  CloudFormation and updates to the AWS StackSet 😉

Update the cloudformation template of watched-accounts with new permissions

---

cloudformation/security-hq.template.yaml

Installs the AWS Inspector package on instances as part of launch config
The AWS Inspector service is available to run reports against.
Yes.
Changes are included but not run.
No.

Add AWS Inspector to launch config

---

cloudformation/security-hq.template.yaml

Remove the AWS Inspector installation code lines from cloud init.
This functionality has moved to an Amigo recipe.
No

Remove AWS Inspector installation from Cloud Init

---

hq/app/utils/attempt/Attempt.scala
hq/app/utils/attempt/Failure.scala
hq/app/utils/attempt/PlayIntegration.scala

Adds log line to unexpected errors.
The application previously assumed that all logging would be done at the edge of the program (in PlayIntegration). This is no longer true because in several areas we have chosen to handle errors ourselves instead of using the automatic error handling provided by Attempt (e.g. in all the cached data). Our own error handling is ok, but does not deal well with unexpected errors so it is important that we log information at these points.
Nope.
It also simplifies an existing logging call along the same lines.
The change adds methods to FailedAttempt to make logging calls simpler. I advocate avoiding mixing data definitions with behaviour. The case where (in my head) it's ok to go against this rule is when the properties added to the data definition are …

Log unexpected errors

---

hq/app/aws/ec2/EC2.scala
hq/test/aws/ec2/EC2Test.scala

cc @katebee I looked at the error messages now we have them. I guess they have unusual instances in their clusters.
Fixes NPE in `EC2.parseNetworkInterface` when the Network Interface is missing.
Will allow Ophan team to look at their SGs again.
No
None

Fix NPE in code to parse EC2 network interfaces

---

hq/markdown/aws-inspector.md
hq/markdown/index.md

Adds documentation of the AWS Inspector lambda + results implementation we will be using.
Explains what Inspector offers and how it will be used.
No.
No.

Add AWS Inspector documentation

---

build.sbt

Disables the sbt assembly plugin for the hq project.
Stops people wasting time trying to use assembly to build a deployable when they should be using dist.
No
No

Disable assembly plugin for Security HQ

---

cloudformation/security-hq.template.yaml

Reverts to installing AWS Inspector at launch instead of in the AMI.
The AMI install failed because the kernel module present from the installer did not necessarily match the running kernel at launch.
Yes.
Yes
No - it is automated by riffraff
No

Re-instate AWS Inspector in Launch Config

---

hq/markdown/aws-inspector.md

Documentation
The originally documented approach did not work, so the documentation reflects new 'best practice'.
No
No

Update AWSInspector documentation to use cloud-init

---

hq/public/stylesheets/main.css

Makes disabled icons grey again
CSS fix
Nope

Fix colour of disabled icon

---

build.sbt
cloudformation/watched-account.template.yaml
hq/app/AppComponents.scala
hq/app/aws/inspector/Inspector.scala
hq/app/controllers/InspectorController.scala
hq/app/logic/InspectorResults.scala
hq/app/model/models.scala
hq/app/utils/attempt/Attempt.scala
hq/app/views/fragments/inspectorResult.scala.html
hq/app/views/fragments/openSecurityGroups.scala.html
hq/app/views/header.scala.html
hq/app/views/iam/exposedKeys.scala.html
hq/app/views/iam/iam.scala.html
hq/app/views/iam/iamAccount.scala.html
hq/app/views/index.scala.html
hq/app/views/inspector/inspector.scala.html
hq/app/views/inspector/inspectorAccount.scala.html
hq/app/views/inspector/inspectorResult.scala.html
hq/app/views/sgs/sgs.scala.html
hq/app/views/sgs/sgsAccount.scala.html
hq/conf/routes
hq/public/javascripts/app.js
hq/public/stylesheets/main.css
hq/test/logic/InspectorResultsTest.scala

Adds AWS Inspector results for each account to the app.
Yes, there is a change to `watched-account.template.yaml` to enable AWS Inspector calls.
**StackSet update required prior to deploy**

Display AWS Inspector results

---

hq/app/AppComponents.scala
hq/app/aws/inspector/Inspector.scala
hq/app/controllers/InspectorController.scala
hq/app/services/CacheService.scala
hq/conf/routes

Puts inspector data into the CacheService.
The page loads quickly and we don't slam AWS if SHQ gets busy.
Nope.
This data is configured to refresh irregularly, so there is a manual refresh endpoint.

Adds inspector data to the CacheService

---

hq/app/logic/InspectorResults.scala
hq/test/logic/InspectorResultsTest.scala

Changes the way we parse assessment runs for the Inspector data.
We now exclude assessment runs that are in progress. We also only show assessments that were created and run by our automated system. Manual invocations will not appear here.
Nope.
Nope.

Properly parse our assessment runs

---

hq/app/views/fragments/inspectorResult.scala.html

Filters on assessment run instead of assessment target when opening the aws console for an inspector result.
It's what is expected.
No.

Filter on assessment runs

---

hq/app/logic/InspectorResults.scala
hq/test/logic/InspectorResultsTest.scala

Support empty Stack/App/Stage tags when looking for inspector runs.
The lambda runner will run *all combos* of stack/app/stage, including ones with missing tags. This will now pick all of them up.
Nope.
Based on https://github.com/guardian/security-hq/pull/114/files <- merge that first

Inspector parsing support empty tags

---

hq/app/AppComponents.scala
hq/app/api/Snyk.scala
hq/app/aws/ec2/EC2.scala
hq/app/controllers/SecurityGroupsController.scala
hq/app/controllers/SnykController.scala
hq/app/logic/SnykDisplay.scala
hq/app/model/Serializers.scala
hq/app/model/models.scala
hq/test/logic/SnykDisplayTest.scala
hq/test/resources/logic/SnykDisplayTest/badResponseWithMessage.json
hq/test/resources/logic/SnykDisplayTest/badResponseWithoutMessage.json
hq/test/resources/logic/SnykDisplayTest/goodAndNotVulnerableResponse.json
hq/test/resources/logic/SnykDisplayTest/goodButVulnerableResponse.json
hq/test/resources/logic/SnykDisplayTest/goodOrganisationResponse.json
hq/test/resources/logic/SnykDisplayTest/goodProjectResponse.json
hq/test/resources/logic/SnykDisplayTest/nogroup.json
hq/test/resources/logic/SnykDisplayTest/nullgroup.json
hq/test/resources/logic/SnykDisplayTest/realgroup.json
package.json

Calls the Snyk API and correctly parses the new form of response (groups).
We have re-organised our Snyk accounts.  This change handles the resulting change in API responses.
It also handles error cases much better.
No.
The token in ssm needs to be changed, as does the the organisation, which now takes the parent group id.

New snyk api

---

cloudformation/security-hq.template.yaml

Remove AWS Inspector agent install from cloud-init
This feature can now be installed via Amigo and should not be installed in cloud-init as it increases
the startup time for an instance.
Yes
Yes 
No
No

Remove Inspector from cloud-init

---

build.sbt
package.json

Upversion Jackson databind and brings all AWS SDK entries in line.
Fixes Jackson value to a single value.
Upversions Snyk tooling.
Removes (hopefully) vulnerabilities reported by Snyk
No
No

Snyk: Upversion Jackson and parts of AWS SDK, and Snyk

---

cloudformation/security-hq.template.yaml

Removes over-generous managed policy for SSM
Adds new, much reduced policy for ssm run-command only
Restructures the CFN Policy resources for clarity
Worked example for other teams to follow
Yes
No
No

Much reduced policy for SSM run-command only

---

hq/app/services/CacheService.scala

Instead of piling in with loads of IO, we let Play start the server and then start caching. Riff Raff waits a bit before finishing deploys, so the impact on the service from this delay should be minimal.
Might fix the "cannto start server" issue.
No
No

Give app more time to start the server in PROD mode

---

build.sbt
hq/app/services/CacheService.scala
hq/conf/logback.xml

Update various caches by Quartz Scheduler instead of Play.
Play threads were hanging around and taking up memory, leading to crashes, leading to instance cycling.  This change does not appear to do that.
No
No

Move to Quartz scheduler

---

hq/conf/application.conf

Increases the initial port binding timeout from 5s to 15s.
Currently, instances are failing at start because the application is failing and so the healthcheck fails.  This should eliminate this failure mode so that we can concentrate on the out-of-memory failure mode.
No
No

Increase initial port binding timeout

---

.gitignore
hq/app/AppComponents.scala
hq/app/aws/AWS.scala
hq/app/aws/cloudformation/CloudFormation.scala
hq/app/aws/ec2/EC2.scala
hq/app/aws/iam/IAMClient.scala
hq/app/aws/inspector/Inspector.scala
hq/app/aws/support/TrustedAdvisor.scala
hq/app/aws/support/TrustedAdvisorExposedIAMKeys.scala
hq/app/controllers/HQController.scala
hq/app/controllers/InspectorController.scala
hq/app/controllers/SecurityGroupsController.scala
hq/app/logic/InspectorResults.scala
hq/app/services/CacheService.scala
hq/app/utils/attempt/Attempt.scala
hq/test/aws/AWSTest.scala
hq/test/aws/cloudformation/CloudFormationTest.scala
hq/test/aws/ec2/EC2Test.scala

Never create AWS Clients on demand, but re-use pre-created clients instead.
AWS Clients wrap thread pools and have their own root threads, and thus are not garbage collected.  If a new client is created, it must be explicitly shutdown to avoid a leak.  Alternatively, create one per account per region at the start, and re-use it forevery.  This is what we have done.
No
No

Re-use all AWS clients

---

.gitignore
build.sbt
hq/app/AppComponents.scala
hq/app/aws/AWS.scala
hq/app/aws/cloudformation/CloudFormation.scala
hq/app/aws/ec2/EC2.scala
hq/app/aws/iam/IAMClient.scala
hq/app/aws/inspector/Inspector.scala
hq/app/aws/support/TrustedAdvisor.scala
hq/app/aws/support/TrustedAdvisorExposedIAMKeys.scala
hq/app/controllers/HQController.scala
hq/app/controllers/InspectorController.scala
hq/app/controllers/SecurityGroupsController.scala
hq/app/logic/InspectorResults.scala
hq/app/services/CacheService.scala
hq/app/utils/attempt/Attempt.scala
hq/conf/logback.xml
hq/test/aws/AWSTest.scala
hq/test/aws/cloudformation/CloudFormationTest.scala
hq/test/aws/ec2/EC2Test.scala

Reverts the previous change which introduced Quartz schedular, and re-instates Observables.
Previous change did not fix the threading problem.
No
No

Jr revert to observables

---

lambda/security-groups/src/main/scala/com/gu/hq/Notifier.scala
lambda/security-groups/src/test/scala/com/gu/hq/NotifierTest.scala

This change will, in particular, cause CODE stacks to emit security groups notifications.

Drop the `Stage`tags from the list of tags sent by lambdaSecurityGroups

---

cloudformation/security-hq.template.yaml

Returns SHQ to a single micro instance
Larger instances / multiple instances are no longer required as the application is stable again.
Yes
No
No

Reduce Security HQ instance size and count

---

cloudformation/security-hq.template.yaml

Reverts my change back to micro, so we go to t2.small permanently.
Previously we had upscaled to small because we suspected memory issues.  Having resolved those, we believed we could downscale again, back to micro.  However it appears that SHQ has grown, and it is now killed on a micro instance.  upscaling to small permanently fixes the issue.
Yes
Yes
No
No

Increase instance size

---

hq/app/logic/InspectorResults.scala
hq/test/logic/InspectorResultsTest.scala

If an account has multiple assessment runs but none of those have any findings, that is different to an account that has no assessment runs (and thus no findings).
Fixes this so it's easy to see all the "results" together, separate to the accounts with no assessment runs
Nope
None

Better logic to sort accounts by assessment runs

---

hq/conf/riff-raff.yaml

Switches Security HQ to Amigo's newly-available 18.04 LTS image and enables encryption.
Updates to the latest LTS and enables disk encryption for Security HQ.
No, this only changes the Riff Raff confirguration in the build artifact.
Security HQ is the easiest place to test this new image. I'll roll it out to Janus next but SHQ already uses systemd so it's a trivial change here.

Switch to use the new Bionic LTS image

---

hq/conf/riff-raff.yaml

Simplifies the deployment AMI resolution, which isn't currently working. This should make it easier to work out what's going wrong.
Fix the AMI update on deploy.
N/A
Nope

Remove amiEncrypted parameter to see if that fixes resolution

---

hq/conf/riff-raff.yaml

Corrects the RiffRaff configuration for Security-HQs AMI.
Allows the service to use an encrypted AMI
Nope
Previously the `amiEncrypted` was erroneously a child of `amiTags` instead of `parameters`.

Correct RiffRaff configuration

---

cloudformation/security-hq.template.yaml
hq/app/AppComponents.scala
hq/app/aws/AWS.scala
hq/app/aws/AwsAsyncHandler.scala
hq/app/aws/AwsClient.scala
hq/app/aws/cloudformation/CloudFormation.scala
hq/app/aws/ec2/EC2.scala
hq/app/aws/iam/IAMClient.scala
hq/app/aws/inspector/Inspector.scala
hq/app/aws/package.scala
hq/app/aws/support/TrustedAdvisor.scala
hq/app/aws/support/TrustedAdvisorExposedIAMKeys.scala
hq/app/aws/support/TrustedAdvisorRDSSGs.scala
hq/app/aws/support/TrustedAdvisorS3.scala
hq/app/aws/support/TrustedAdvisorSGOpenPorts.scala
hq/app/model/models.scala
hq/app/services/CacheService.scala
hq/app/utils/attempt/Failure.scala
hq/test/aws/AWSTest.scala
hq/test/aws/ec2/EC2Test.scala

Security HQ has been down / flaky for a while and was tricky to troubleshoot.
The initial failure was down to AWS launching a new region which didn't exist in the SDK version we were using:
```scala
describeAwsRegions.map(Regions.fromName)
```
It turns out this was done for good reasons - we want to process all regions but not Chinese or the US GovCloud as both of these need special AWS accounts. The `describeAvailableRegions` command will only include regions you can access, but will also include regions that are not in your SDK.
In initially fixing this we accidentally tried to run security HQ against China/GovCloud and this was hard to troubleshoot as there was no context of the account or region at the call site.
To solve this we introduced context via an `AwsClient` case class which …

Fix region assumptions, increase instance size and overhaul AWS SDK failure logging

---

cloudformation/security-test-user.yaml
hq/README.md
hq/app/AppComponents.scala

[dev-nginx](https://github.com/guardian/dev-nginx) contains a number of generic useful scripts to:
- issue certs locally (and automatically trust them)
- [generate an nginx config file](https://github.com/guardian/dev-nginx#setup-app) from a yaml definition
Tried running the app today locally and ran into an error:
I probably ran into this due to not having `ec2:DescribeRegions` on my DEV user, so I have also given myself the missing permissions.
Any strong feelings on switching to using getOrElse? This allows SHQ to still run if ec2:DescribeRegions` is missing from a policy.
This template includes minimal permissions for running Security HQ locally against a single account:
This means that setting up a dev environment no longer requires access to a specific AWS account.
Ideally, this …

Revisions for DEV setup and new CFN template for DEV user

---

hq/app/aws/iam/IAMClient.scala
hq/app/aws/support/TrustedAdvisorS3.scala
hq/app/controllers/BucketsController.scala
hq/app/controllers/CredentialsController.scala
hq/app/controllers/SecurityGroupsController.scala
hq/app/logic/CredentialsReportDisplay.scala
hq/app/logic/PublicBucketsDisplay.scala
hq/app/model/models.scala
hq/app/services/CacheService.scala
hq/app/views/fragments/allKeyStatus.scala.html
hq/app/views/iam/iam.scala.html
hq/app/views/iam/iamCredReportBody.scala.html
hq/app/views/s3/publicBuckets.scala.html
hq/app/views/s3/publicBucketsAccount.scala.html
hq/app/views/s3/publicBucketsBody.scala.html
hq/test/logic/CredentialsReportDisplayTest.scala
hq/test/logic/PublicBucketsDisplayTest.scala

- An account with errors will be above one with lots of warnings
- An account with a failed response from AWS will appear after others
- A bucket with report status `Red` will be above one with report status `Amber`
- Buckets with equal report status severity will be sorted alphabetically
- Add logic to sort bucket report information
- Counts the total reports along with warnings and errors
- Adds bucket details summary information to the account display
Nope
The Trusted Advisor report actually includes all buckets, even if they are status green therefore this PR renames the class and some methods to better express what we are actually getting from Trusted Advisor. 
Next steps will be to filter suppressed buckets from the view and to add details and warnings around bucket encryption …

Order accounts and buckets but report status

---

build.sbt
cloudformation/security-test-user.yaml
cloudformation/watched-account.template.yaml
hq/app/AppComponents.scala
hq/app/aws/AWS.scala
hq/app/aws/support/TrustedAdvisorS3.scala
hq/app/logic/PublicBucketsDisplay.scala
hq/app/model/models.scala
hq/app/services/CacheService.scala
hq/app/views/fragments/bucketsHelp.scala.html
hq/app/views/s3/publicBuckets.scala.html
hq/app/views/s3/publicBucketsAccount.scala.html
hq/app/views/s3/publicBucketsBody.scala.html
hq/public/javascripts/app.js
hq/test/logic/PublicBucketsDisplayTest.scala

Adds bucket encryption status to Security HQ so that there is a single place we can view all buckets that do not have encryption-at-rest enabled.
> Amazon S3 default encryption provides a way to set the default encryption behavior for an S3 bucket. You can set default encryption on a bucket so that all objects are encrypted when they are stored in the bucket.
https://docs.aws.amazon.com/AmazonS3/latest/dev/bucket-encryption.html
Unfortunately, the encryption status for a bucket requires yet another set of AWS clients. This PR adds S3 clients so that we can call `s3:GetEncryptionConfiguration` on each bucket.
If there is no bucket encryption, AWS will return  an error. The current code assumes that the bucket is not encrypted if `getBucketEncryption` throws an `AmazonS3Exception` and this …

Add bucket encryption status to Security HQ

---

build.sbt
cloudformation/security-hq.template.yaml
hq/app/AppComponents.scala
hq/app/AppLoader.scala
hq/app/config/Config.scala
hq/app/config/LoggingConfig.scala
hq/app/logging/LogConfig.scala
hq/app/model/models.scala
sbt

Adds log shipping in two different flavours:
- Remote shipping to the central-ELK stack via Kinesis and the [`kinesis-logback-appender`](https://github.com/guardian/kinesis-logback-appender).
- Local log shipping to a [`local-elk`](https://github.com/guardian/local-elk) stack. This is just to provide a simpler interface for log interrogation compared to `grep` and others.
Shipping logs to an ELK stack provides a simpler interface for interrogation.
Shipping logs to a remote ELK stack will mean one no longer needs to ssh onto an instance to observe logs generated by the application.
No.
This is heavily inspired by the Editorial Tools, for example [Workflow Frontend](https://github.com/guardian/workflow-frontend/blob/ca3789371031d52caaced42103740fbfd57c96b1/common-lib/src/main/scala/com/gu/w …

log shipping

---

cloudformation/security-hq.template.yaml

This policy has been copied from the [ssm-scala docs](https://github.com/guardian/ssm-scala#how-to-use-ssm-scala-with-your-own-project).
Currently `ssm ssh` is yielding:
```console
An error occurred (TargetNotConnected) when calling the StartSession operation: i-000000000000 is not connected.
kex_exchange_identification: Connection closed by remote host
```
Enabling us to connect to an instance.
CFN changes, yes.
n/a

expand the ssm policy with permissions required for SSH over SSM

---

cloudformation/security-hq.template.yaml

For a long time at The Guardian it has been possible to SSH without opening up port 22, thanks to [SSM-Scala!](https://github.com/guardian/ssm-scala)
Along with removing the requirement to have port 22 open, SSM-Scala also provides visibility into which instances have been accessed and removes the requirement for bastions (thanks to ssm-tunnelling!) The latest version of SSM-Scala - 2.0.0 - sets SSM tunnelling as the default behaviour.
SSM-Scala should therefore be the default way we access instances.
This changes the security groups of several instances so that the Wazuh agents can register with the Wazuh manager and send events to the Wazuh cluster.
- Port 1514 is used for agent event logging
- Port 1515 is used for agent registration
Describing region, tags and ASG is required so that …

Remove SSH access, add egress for wazuh agents

---

sbt

Modifies the SBT script for security HQ  so that more memory gets allocated on startup. The Xmx property specifiies "the maximum size, in bytes, of the memory allocation pool. "
With this one simple trick...run security HQ locally for > 5 mins without crashing.

Allocate 4GB of memory to SBT on startup

---

build.sbt
hq/app/AppComponents.scala
hq/app/aws/AWS.scala
hq/app/aws/ec2/EC2.scala
hq/app/aws/ec2/EFS.scala
hq/app/logic/SecurityGroupDisplay.scala
hq/app/model/models.scala
hq/app/services/CacheService.scala
hq/app/views/fragments/openSecurityGroups.scala.html
hq/test/aws/ec2/EC2Test.scala
hq/test/aws/ec2/EFSTest.scala
hq/test/logic/SecurityGroupDisplayTest.scala

Security HQ does not recognise AWS Elastic File Systems. This means that when an EFS security group is flagged by Trusted Advisor (because for example it has ports open to the world and is therefore a security risk), the `/security-groups` endpoint does not give us the file system id and corresponding link to it in the AWS console. 
We've now added the capability for Security HQ to recognise EFSs.
| Before      | After* |
| ----------- | ----------- |
| <img width="273" alt="Screenshot 2021-02-05 at 13 24 00" src="https://user-images.githubusercontent.com/42121379/107039172-6ec3cf80-67b5-11eb-9882-af4bfc360a15.png"> | <img width="273" alt="Screenshot 2021-02-05 at 13 23 52" src="https://user-images.githubusercontent.com/42121379/107039195-78e5ce00-67b5-11eb-96a4-d51f35b9880c.png"> | …

Adds Elastic File System (EFS)

---

build.sbt
hq/app/config/Config.scala
hq/app/logic/DocumentUtil.scala
hq/app/model/models.scala
hq/app/views/documentationHome.scala.html
hq/public/stylesheets/main.css

This PR:
- Reduces font size of the docs so you don't have to zoom out
- re-enables bullet point in unordered lists (disabled by materialize by default)
- Pulls the data driving the [documentation index page](https://security-hq.gutools.co.uk/documentation) out of the template to reduce boilerplate
- Adds Wazuh to the documentation index
Docs are more readable and findable 🥳 
Before
After

Improve documentation pages

---

hq/app/views/header.scala.html
hq/public/javascripts/app.js

Adds some tooltips to the menu to identify what each icon does.
Usability. A better option would arguably be labels but they probably wouldn't fit, and this is a super quick and easy option.
No

Add tooltips for menu items

---

.github/CONTRIBUTING.md

We're trying to get rid of the master branch at the guardian. Some details here https://github.com/github/renaming. I've already renamed the branch on this repo, this PR updates the docs accordiingly

Replace references to master branch

---

hq/markdown/wazuh.md

This change replaces a suggestion to ssh onto instances to check if Wazuh is running correctly with a `ssm cmd` command that should save people some time. I've also mentioned that people can just contact DevX to get someone to check whether it is working correctly, which I think makes sense for early adopters - we want to help them out as much as possible.

Simplify Wazuh Agent Setup docs

---

cloudformation/security-hq.template.yaml
hq/conf/riff-raff.yaml

This updates the referenced recipe for security HQ to a [new arm64 recipe](https://amigo.gutools.co.uk/recipes/security-java-lts-arm64) and parameterises the instance type within the security HQ cloudformation to make switching to a t4g easier. 
This change is currently live on PROD and doesn't seem to be causing any issues
$$$ savings and maybe performance increase?!

Security HQ>>>ARM64 💪🏻 🚀 

---

hq/markdown/vulnerability-management.md

Following a meeting with Infosec, this change adds out of date AMIs to the 'critical vulnerabilities' list.

Add old AMIs to critical vulnerabilities list

---

hq/markdown/wazuh.md

Turns out the code snippet I copy pasted from somewhere was missing a property!
I've also remembered that amiable can list ami images by account, which for the purposes of the wazuh rollout is the most convenient thing ever thanks @philmcmahon

Tweaks to wazuh documentation

---

build.sbt
hq/app/AppComponents.scala
hq/app/config/Config.scala
hq/app/controllers/GcpController.scala
hq/app/logic/GcpDisplay.scala
hq/app/model/models.scala
hq/app/services/CacheService.scala
hq/app/views/gcp/gcp.scala.html
hq/app/views/gcp/gcpReportBody.scala.html
hq/conf/application.conf
hq/conf/routes
hq/public/stylesheets/main.css
sbt

This PR adds a new route, `/gcp`, to show Google Cloud Platform (GCP) security vulnerabilities for each project in the Guardian organisation.
We at the Guardian generally use AWS for our cloud infrastructure needs, but have recently increased our usage of GCP. Given this, it's vital that we include GCP assets in our security monitoring. 
This work is the Guardian's first major project to expose GCP security vulnerabilities so that engineering teams can easily see the remediation steps required for them to run their GCP infrastructure securely. 
This PR should be seen as a minimum viable product, because there is still lots of work to do before this is ready to present to the department. Here are some of the major things on our TODO list after this PR is merged:
- add a /gcp link to the …

Add GCP security vulnerabilities

---

README.md

This PR adds documentation about the local config files required to run Security HQ locally. 
The `security-hq.local.conf` file has been put into S3 so that developers running Security HQ for the first time do not have to find a colleague to give it to them, but can instead copy it from S3 themselves.

Update readme with new process for getting local conf

---

hq/app/views/header.scala.html
hq/app/views/iam/iam.scala.html
hq/app/views/index.scala.html
hq/app/views/main.scala.html
hq/app/views/s3/publicBuckets.scala.html
hq/app/views/sgs/sgs.scala.html

This PR adds the GCP logo and link to the homepage and to the headers of the other pages.
Users can now navigate to /gcp from other pages without manually typing it into the browser!

Add GCP link to all pages

---

hq/app/logic/GcpDisplay.scala
hq/app/model/models.scala
hq/app/views/gcp/gcpReportBody.scala.html
hq/public/stylesheets/main.css

I took a little too much of the CSS out of #198 post code review, which led to the table text overflowing out of the table. Adding the CSS back in here to fix it, so that the text remains within the table!
Also, this PR adds "Unknown" for missing severity values.

Manages missing GCP severity values and fixes styling

---

build.sbt
hq/app/logging/Cloudwatch.scala
hq/app/logic/PublicBucketsDisplay.scala
hq/app/services/CacheService.scala

This makes Security HQ post the results of its data collection to cloudwatch as a metric. It's powering this [grafana dashboard](https://metrics.gutools.co.uk/d/RHAvkh8Gz/securityhq?orgId=1&from=now-2d&to=now). The data collected is based [on this original proposal](https://docs.google.com/document/d/1PIZC67-RymEYrtpOWLy18vAV8hRqjh67yBy4UezQoTQ/edit), but the key difference is in this PR I've only implemented 4 data types to reflect "totals". Namely
* Total number of S3 buckets `s3/total`
* Total number of IAM credentials marked red `iam/credentials/critical`
* Total number of IAM credentials marked amber `iam/credentials/warning`
* Total number of IAM credentials red or amber `iam/credentials/total`
* Total number of exposed keys `iam/keys/total`
* Total number of public security groups …

Post metrics to cloudwatch

---

hq/app/logging/LogConfig.scala
hq/conf/logback.xml

This modifies both what gets printed to the console and gets sent to central elk.
Currently, central elk is not getting much of anything sent to it, so the data isn't very useful!
When developing locally, it's useful to see more logs in the console than just errors
No

Set loglevel to info

---

cloudformation/security-hq.template.yaml

Lets Sec HQ post metrics to cloudwatch
Getting #202 to actually work!
Indeed!

Allow Sec HQ to post metrics to cloudwatch

---

hq/app/AppComponents.scala
hq/app/logging/Cloudwatch.scala
hq/app/services/CacheService.scala
hq/app/services/MetricService.scala

This PR changes the data collection approach quite a bit. Instead of piggy backing off the existing CacheService, which has a refresh cadence of 5 minute updates for security groups and S3 and 90 minutes for iam, this PR creates an independent MetricService which runs once every 6 hours and fetches the latest data produced my CacheService.
The value is twofold.
First, posting new metrics every 5 minutes is unnecessary for this data's usecase. It's too much resolution for a dataset where we care about daily and weekly trends. We also hit cloudwatch limits when trying to retrieve weeks of data if there's too many datapoints.
Secondly, this PR avoids posting to cloudwatch if the dataset is incomplete. This is slightly counter intuitive, at first glance that's not good because it means we're …

Move cloudwatch code to its own MetricService

---

.github/workflows/snyk.yml

Run Snyk as a GitHub Action.
Notes:
- I do not have access to the org in snyk.io but I believe `guardian-security` is the one this repo is under. If someone with access could confirm it before this is merged it would be great though.
- I do have access to this repo's settings to check if `SNYK_TOKEN` is available. I believe it is but if someone with access could double check I'd appreciate it.
Implements the the preferred method of integrating Snyk introduced in PR #212.
After this is merged and confirmed working the original project entry in snyk.io and the Snyk hook configured in GitHub can be removed. If there are any build steps in TeamCity that run Snyk, those can be removed too.

Run Snyk as a GitHub Action

---

hq/markdown/snyk.md

This PR changes the instructions on how to integrate Snyk to use GitHubs Actions instead of Snyk's GitHub integration.
Snyk's GitHub integration can lead to number of issues, such as lack of immediate feedback or repo scans failing silently. This often leads developers to opt by using CLI integration alongside it. However, CLI integration also has its shortcomings and limitations.
Furthermore, using one or both of these integrations mean that the Snyk config is spread through different systems (Snyk website, GitHub hooks config, local scripts, TeamCity build steps, etc.), making it difficult for new developers to easily understand the Snyk workflow. 
Using GitHub Action to run Snyk solves these and other issues, making it the superior choice for integration.
It consistently updates …

How to integrate Snyk using GitHub Actions

---

hq/app/views/gcp/gcp.scala.html
hq/app/views/gcp/gcpReportBody.scala.html
hq/app/views/s3/publicBuckets.scala.html
hq/app/views/s3/publicBucketsAccount.scala.html
hq/public/javascripts/app.js
hq/public/stylesheets/main.css

This PR adds checkboxes to filter GCP security findings by severity.

Add filtering on severity

---

hq/app/model/models.scala
hq/app/services/CacheService.scala

This PR returns test data for /gcp when running SHQ locally. 
It should make development work on /gcp easier whilst improving the styling of the page. Prior to this change, it was taking around 4 minutes to return the data from the GCP API.
I attend to revert this commit once I've completed my styling work.

adds dummy data for /gcp

---

hq/markdown/guardduty-sechub-common-problems.md

This adds more detail on the IMDSv2 guidance documentation - specify the exact AWS SDK versions required for it to work and highlighting an issue with the simple configuration library

Improve imdsv2 docs

---

hq/app/views/gcp/gcp.scala.html

This PR changes the showing of the severity value summary icon on each row of the /gcp table. Now the icon is only shown when this value is great than zero. This is an improvement on PR https://github.com/guardian/security-hq/pull/217.
This is so much better than when we were showing each icon everytime, because there is less noise on the UI. It's easier to see where the red high severity findings are. Hopefully this should make it easier for developers to see at a glance where they should prioritise their gcp security efforts.
Also, this change follows the pattern already used in SHQ in the S3 buckets and IAM report tables.

Shows severity value icon on /gcp if greater than zero

---

hq/app/services/CacheService.scala
hq/app/utils/attempt/Failure.scala

The current error message on /gcp is misleading as it says `error-missing data` and doesn't tell the user how they should remediate this problem. 
We've made the message friendlier and given the user an action to take.

Friendly error msg whilst GCP cache loading

---

hq/app/logic/GcpDisplay.scala
hq/app/views/gcp/gcpReportBody.scala.html
hq/public/javascripts/app.js
hq/public/stylesheets/main.css

This PR adds a read more/less toggle button to text inside the GCP table.
Quite a lot of text is returned in some of the cells, so this toggle button should make it easier for users to select the text they want to see and skim over what they don't need to read.

Adds Read more/less toggle button

---

hq/markdown/wazuh.md

Updates the grep command in the Wazuh guide to include permissions errors in the wazuh agent's output at startup.
Without it, permissions errors present in this output are hidden and may go unnoticed.

Update grep command to display permissions errors

---

build.sbt
hq/app/model/models.scala
hq/app/schedule/CredentialsNotifier.scala
hq/app/schedule/CredentialsReportJob.scala
hq/app/schedule/CronSchedules.scala
hq/app/schedule/JobRunner.scala
hq/app/schedule/JobScheduler.scala
hq/app/schedule/JobWrapper.scala

This PR starts the work of adding a scheduler and notification service to security hq. 
The aim is to send automated notifications about insecure credentials.
Ideally, every week (or another time period!) SHQ will check the ages of all permanent credentials. If the age is > 90 days an email will be sent to the email address associated with the AWS account contained in anghammarad. (A follow up piece of work is, if the age goes over 120 days (or another time period!) delete the credentials!)
The scheduling service is reusable, so if in the future we would like SHQ to send notifications for other reasons, this is possible.
1. Complete createMessage function
2. Address TODOs
3. Write tests

Add notifier

---

hq/public/stylesheets/main.css

I noticed in the GCP Security Findings section (https://security-hq.gutools.co.uk/gcp) that the words in the 'Explanation' column were all splitting exactly at the right-hand edge - sometimes it's necessary to split words in layout because they're just too long to ever fit (eg `AUDIT_LOGGING_DISABLED` might never fit in the column space) but for shorter words it's unnecessary to split them in half, when you can just let the whole word flow onto the next line - although it's relatively new behaviour, CSS does support this, with the [`overflow-wrap`](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap) property (rather than `word-wrap` & `word-break`).
I've only tried this by experimenting in Chrome Dev Tools, not actually run Security HQ with these changes, so I may have made a …

Try to break words less often with overflow-wrap

---

hq/app/logic/DateUtils.scala
hq/app/services/CacheService.scala
hq/app/views/iam/iamCredReportBody.scala.html

This change essentially backfills missing credentials reports with existing ones.
It does so by looking at the result from the fetch and replacing tuples with "left"  with tuples with the data currently in memory.
The idea here is that it's more valuable to display the last known good report rather than an error message like this
The age of the report is displayed up top but it doesn't do anything clever to highlight that a report is older than it should be. Given that it's fetched every 90 minutes, I'd expect that the api rate limiting issue wont' leave us with very old reports.
Nope
This is probably a little hacky, but we do intend to solve the root cause of the issue (which is the way we're fetching data causing us to be API rate limited) next week or the week after.

Show stale data on credential report failure

---

hq/app/logic/GcpDisplay.scala
hq/app/model/models.scala
hq/app/views/gcp/gcp.scala.html
hq/app/views/gcp/gcpReportBody.scala.html
hq/public/javascripts/app.js

This change:
- Increases page size of GCP queries to 1000 (the default is 10)
- Adds an extra filter to only show 'active' findings - GCP Security centre keeps a record of all security events that have happened, but we only care about current ones
- Switches the 'severity' value being used to the one at the top level of the finddings object.
- The GCP query now loads more quickly as it involves fewer requests thanks to the larger page size. 
- We aren't showing non-active findings to users
- We have fewer 'unknown severity' findings as the top level severity property seems to be more frequently set.
No

GCP Dashboard Improvements

---

hq/markdown/guardduty-sechub-common-problems.md
hq/markdown/snyk.md
hq/markdown/vulnerability-management.md

This change:
- adds docs for excluding vulnerabilities
- adds docs for jackson databind Snyk issues
- adds docs for instances with a public ipv4 address
- Swaps guard duty  and security hub around in the list of stuff to look at

Update security docs

---

hq/app/views/gcp/gcp.scala.html

This removes an erroneously placed icon from the top of the GCP dashboard

Remove floating icon

---

cloudformation/watched-account.template.yaml

Adds an extra permission to allow security HQ to fetch IAM tags. These will be used to determine which teams to alert about problematic IAM users, and maybe in the UI to make it clearer who owns what
Yes - I haven't done this yet though pending this PR https://github.com/guardian/janus/pull/2643

Allow security hq to listusertags

---

hq/app/logging/Cloudwatch.scala
hq/app/services/MetricService.scala

This patch adds logging of GCP high and critical vulnerabilities to cloudwatch alongside the existing AWS vulnerabilities metrics.
The fact that GCP vulnerabilities have a project, as opposed to AWS vulnerabilities which have an account, means that their respective cloudwatch metrics will have different dimensions, which means they will have different schemas.
Accounting for this requires a refactor of putMetric into something
parameterised that can be used for both cases.
We'll be able to add gcp vulnerabilities to the security dashoard
Nein
Unlike for example `cacheService.getAllSgs` which basically returns an `Either` that can be unpackaged using pattern matching, `cacheService.getGcpFindings` returns an `Attempt` which I think needs to be unpackaged using a for comprehension? It seems …

Log GCP vulnerabilities to cloudwatch metrics

---

hq/app/logging/Cloudwatch.scala

There's a bug in the GCP metrics code. Current code is sending a `Vulnerabilities` metric per GcpProject, but instead of listing only the findings for that project it's counting _all of them_. So currently every GcpProject is listed as having 5 high vulnerabilities. In reality almost all of them have 0, except one that has 3 and another which has 2.
Getting correct data in cloudwatch.

Use only findings belonging to the current project

---

hq/app/AppComponents.scala
hq/app/aws/ec2/EC2.scala
hq/app/aws/iam/IAMClient.scala
hq/app/logic/CredentialsReportDisplay.scala
hq/app/model/models.scala
hq/app/schedule/IamAudit.scala
hq/app/schedule/IamJob.scala
hq/app/schedule/IamNotifier.scala
hq/test/aws/ec2/EC2Test.scala
hq/test/logic/CredentialsReportDisplayTest.scala
hq/test/model/TagTest.scala
hq/test/schedule/IamAuditTest.scala

This PR does two things:
- Sets security HQ up to enrich the data it gets from the IAM report with IAM User Tags. The current approach is to fail an entire report if the call to 'describe tags' for any of the users within the report fails. This isn't very resilient, and may need more work in future so that even if the tag fetch fails, the IAM report is still available. This work is all in this commit https://github.com/guardian/security-hq/commit/0d92708246498a7a9ab4b96c8aa0571c0a5cabdf **this feature is currently disabled**
- Modifies `makeCredentialsNotification` so that it splits notifications into groups based off the  tags of the users with issues. Each group has a list of Targets, which are used by anghammarad to determine where to send the alert to. There's a fairly awkward …

Store tags of IAM users and use them to power anghammarad alerts

---

build.sbt
cloudformation/security-hq.template.yaml
hq/app/AppComponents.scala
hq/app/config/Config.scala
hq/app/model/models.scala
hq/app/schedule/CronSchedules.scala
hq/app/schedule/Dynamo.scala
hq/app/schedule/IamAudit.scala
hq/app/schedule/IamJob.scala
hq/app/schedule/IamNotifier.scala
hq/conf/application.conf
hq/test/schedule/IamAuditTest.scala
setup-local-dynamo.sh

This PR adds dynamoDB so that Security HQ's IAM notification job can record which notifications have been successfully
sent. 
The aim is that this data will be used for two reasons. 
First, so that a new feature, the Credentials Reaper, can be built which automatically disables permanent credentials which are either deemed too old or are missing multi factor authentication. This new feature should only disable a credential if 2 notifications have been sent, hence the need to store data on whether the notification has been sent in a database.
The second reason is that we hope this data will provide a helpful audit trail for Infosec.
This work was tested locally using this https://github.com/aws-samples/aws-sam-java-rest. Here are the steps to use this:
start the server: `docker run -p …

add dynamoDB and put notification data

---

hq/app/model/models.scala
hq/app/schedule/Dynamo.scala
hq/app/schedule/IamAudit.scala
hq/app/schedule/IamJob.scala
hq/app/schedule/IamNotifier.scala
hq/test/schedule/IamAuditTest.scala

This PR follows the work started in PR #247 on the credentials reaper feature, which aims to disable vulnerable permanent IAM credentials. 
This particular change gets data from a DynamoDB table to check whether a notification has already been sent to a user about a vulnerable credential.
This is valuable, because the reaper feature will send 2 alerts before disabling a credential and will need to check if this has happened before doing so.
The next piece of work on this feature is to check the type of notification sent, which is stored in dynamoDB and change the alert message based on this.

☠️ Credentials Reaper - check if alert already sent

---

hq/app/aws/iam/IAMClient.scala

This PR follows  from https://github.com/guardian/security-hq/pull/238 but changes the behaviour. Previously, if a get tags request for any of the users listed in a credential report for an AWS account failed, then the entire report would fail to generate. This modifies the 'enrich with tags' function so that it just returns the report with no tags added in the event that the get tags request fails
Security HQ polls multiple accounts, there's quite a high risk of failure due to issues with the stack set that gives it the permission to crawl an account, or just general network failure. The dashboard should show as much information as possible rather then failing because the tags are missing. 
No

Improve resiliency of IAM tag fetching

---

hq/app/model/models.scala
hq/app/schedule/IamAudit.scala
hq/app/schedule/IamMessages.scala
hq/test/schedule/IamAuditTest.scala

Writing the credentials reaper feature managing two separate user case classes was becoming cumbersome. There was one user type for keys which are old and the other for keys that are missing mfa. Each change to the users required double the code to handle each user type. This change makes it easier to complete the credentials reaper feature.
The downside of this change is that the email alert to users will not include why the user has been flagged. This shouldn't be a major problem as these details are including on the security HQ dashboard.

Merge two vulnerable user types into one

---

hq/app/schedule/IamAudit.scala
hq/app/schedule/IamMessages.scala
hq/app/schedule/IamNotifier.scala
hq/test/schedule/IamAuditTest.scala

Security HQ's IAM alerts send an email to a Guardian AWS account if one of the users in this account has permanent credentials which need rotating or are missing multi factor authentication.
Currently one generic email is sent on a monthly basis. The credentials reaper feature will send two emails; a warning email (similar to the current one) and a final email notifying the AWS account that the problematic permanent credential will be disabled the next day. 
Other credentials reaper PRs: #247 and #249.
This change makes it possible for SHQ to determine which text it should send in the email; the warning text or the final text.
It determines this by checking the deadline that is assigned to the problematic permanent credential. If the deadline is tomorrow, SHQ knows to send a final email. …

IAM alert message determined by flagged user deadline

---

hq/app/AppComponents.scala
hq/app/controllers/CredentialsController.scala
hq/app/model/models.scala
hq/app/schedule/Dynamo.scala
hq/conf/routes
setup-local-dynamo.sh

This PR adds a new route, which returns all of the data in the IAM dynamoDB table. This is useful because a) it's helped us
test that PR #256 works! and b) it means that any user can see which alerts have been sent and what the deadlines are on any flagged credentials.

Add endpoint to get historical IAM alerts report

---

hq/app/aws/iam/IAMClient.scala
hq/app/views/iam/iamCredReportBody.scala.html

This change adds a 'recover' step to aws sdk requests to fetch tags for the user for when the request fails. It also simplifies the logic around enriching a credentials report with tags (https://github.com/guardian/security-hq/pull/251/commits/dd99f32d35e4dd1c84a4f4bcc9928c4032b8a4ac).
Also, expose the Stack tag in a column in the IAM report ui to make it easier to distinguish credentials in the same account being managed by different teams, it looks like this:

Make tag fetching more resilient, show stack tag in IAM report table

---

hq/app/schedule/CronSchedules.scala
hq/app/schedule/IamJob.scala

The IAM job sends notifications when a permanent credential either needs rotating or needs multi-factor authentication.
Currently the job runs monthly, because previously it was just sending one email notification.
Now, it sends up to three notifications over a period of three weeks, alerting the AWS account which holds this permanent credential that it will be disabled if unchanged. Here are the PRs: #256 and #252.
Given this change, the job now needs to run daily in order to implement this new functionality.

Change IAM job CRON schedule to daily

---

cloudformation/watched-account.template.yaml

Currently Security HQ sends AWS accounts an email alert when they have a user with a permanent credential which needs rotating or lacks multi-factor authentication.
The next step for this feature is to create what we call the Credentials Reaper, which disables access keys if they have not been rectified after being notified.
In order to do that, SHQ needs IAM permissions to make an access key inactive.

Adds IAM UpdateAccessKey permission

---

hq/app/controllers/CredentialsController.scala
hq/app/schedule/IamJob.scala
hq/app/schedule/IamNotifier.scala
hq/app/schedule/JobRunner.scala
hq/conf/routes

Creates a route to send notifications to a test anghammarad target, which uses this google group: https://groups.google.com/a/guardian.co.uk/g/anghammarad.test.alerts?pli=1. 
This is great, because it means we can more easily test the email notifications.

Endpoint for testing notifications

---

hq/app/aws/iam/IAMClient.scala
hq/app/model/models.scala

The work in https://github.com/guardian/security-hq/pull/238 resulted in a lot of noisy errors appearing in security HQ logs. This was due to Security HQ making a `ListUserTagsRequest` for users with invalid usernames. I think the culprit here is the root user, which appears to get returned in the credentials report, but has angle brackets in the username: `<root_user>`. The error message we get states `The specified value for userName is invalid. It must contain only alphanumeric characters and/or the following: +=,.@_- ` - excluding the root user should reduce the noisy logging
Less noisy logs, fewer requests to AWS which fail every time

Exclude root user from tag lookup

---

hq/app/schedule/Dynamo.scala
hq/app/schedule/IamJob.scala
hq/app/schedule/IamMessages.scala
hq/app/schedule/IamNotifier.scala
hq/app/schedule/JobRunner.scala
hq/app/schedule/JobWrapper.scala
hq/conf/application.conf

The test and get notifications endpoints were not working. This PR fixes the dynamoDB parsing fields, which were incorrect. It removes the default parameter and corrects a log line. This change has been tested on PROD and locally.

Fix testing and get notifications endpoints

---

hq/app/AppComponents.scala
hq/app/schedule/CronSchedules.scala
hq/app/schedule/IamJob.scala

This change stops the IAM job from running, which means that no notifications about permanent credentials will be sent to colleagues. However, the test endpoint /iam/test-notifications, still works so we will be able to continue testing this feature.
When the credentials reaper feature is ready to be released to PROD the line in app components can be uncommented.

Turn off the IAM job

---

hq/app/model/models.scala
hq/app/schedule/Dynamo.scala
hq/app/schedule/IamAudit.scala
hq/app/schedule/IamJob.scala
hq/app/schedule/IamNotifier.scala
hq/test/schedule/IamAuditTest.scala

Security HQ sends emails to AWS accounts which have permanent credentials that pose a security risk. After making some changes to this feature in order to implement the credentials reaper (this will automate the disabling of credentials), the tests on PROD showed that more than one email was being sent per AWS account. Sometimes the emails would include a subsection of the flagged users, instead of all flagged users in one email. 
We've fixed the code that was causing multiple emails to be sent. 
In addition, we also added that only the ophan account should split emails by tags, as this AWS account is shared by both the ophan and data lake teams. We did this, because it was causing emails to be split by stack for all the AWS accounts when the benefit of this was not clear for other teams. …

Fix duplicate IAM notification alerts

---

README.md

Adds a clarifying note to the start of the AWS configuration section in the README. After some deliberation, we think this section was written with the non-Guardian user in mind (because otherwise using Janus credentials is fine).
Less confusing set-up steps (I was certainly stumped why that section was necessary)
No
No

Clarify credentials section of README

---

hq/app/controllers/GcpController.scala
hq/app/logging/Cloudwatch.scala
hq/app/services/CacheService.scala
hq/app/services/MetricService.scala
hq/app/views/gcp/gcp.scala.html

This fixes an issue where the GCP report findings each claimed to have been generated at the current time, rather than when the report was actually run (every 4 hours, and when redeployed).
Instead of creating a `GcpReport` type, which contains the report time, during the lifecycle of the request, we instead make that the type stored by the GCP `box` in the cache service and write the current date/time when the data is fetched from GCP and the box is filled in the `CacheService`.
Accurate report dates on the GCP page.
No
No

Use report time instead of `now` for GCP report

---

hq/app/schedule/IamMessages.scala

Security HQ sends email notifications when IAM permanent credentials are vulnerable. Currently the email formatting is a little bit confusing, because there's a lot of text. 
As a quick fix, this PR adds a line of dashes, which gmail formats quite nicely as a line that runs across the email dividing the part of the email that details the flagged users and the part of the email that describes where to go for more information.
Hopefully this quick fix helps the readability of the email for readers! You can see what this looks like by checking out the latest test emails here in this google group: https://groups.google.com/a/guardian.co.uk/g/anghammarad.test.alerts

Improve formatting of IAM notification emails

---

hq/app/schedule/IamNotifications.scala

The problem was that the IAM notification emails sent by security HQ (to alert users that there is a vulnerable permanent credential in their account) were missing the deadline field.
The deadline field is really important, because this is the date when SHQ would automatically disable the credential if no change has been made to rectify the problem!!
This PR fixes this by ensuring that the logic which creates the email messages uses an existing function that creates a deadline if it does not already exist.
This may be the case if the credential is being alerted for the first time and is therefore not present in dynamoDB.
This has been tested using the /iam/test-notifications endpoint which sends test emails to this google group: https://groups.google.com/a/guardian.co.uk/g/anghammarad.test …

Fixes missing deadline field in IAM email alerts

---

hq/app/schedule/IamDisable.scala
hq/test/schedule/IamNotificationsTest.scala

This PR adds logic to pull the data from dynamoDB that tells us if an AWS account has been alerted about users with vulnerable permanent credentials in their account.
It checks to see if there are any deadlines that should be disabled today. Unit tests have been added to check that the DateTime check is working. I'm happy that the logic for pulling from the db is working as `scanAlert` is very similar to `getAlert` and is currently working nicely in PROD.

Should security HQ disable a user today?

---

hq/app/logic/CredentialsReportDisplay.scala
hq/app/model/models.scala

I've been looking at updating the way that the report status is determined in the IAM Credentials Report, so that it better matches our expectations regarding credentials rotation. _However_ there were a few small refactors of the logic around the report that I feel improve readability. On first reading I found some of these areas of the logic to be hard to understand, so the hope is that this helps.
There is a further refactor that'd be worth doing that's closer to the logic I actually need to change around outdated credentials. However I'm leaving that until #283 is merged, because I think there will be overlap. That may mean we implement the change itself and come back for the refactor.
Less code, more readable code (some of that is subjective)
No
No

Credentials report refactoring

---

hq/app/config/Config.scala
hq/markdown/vulnerability-management.md
hq/markdown/wazuh.md

- Fixes typo on docs main page
- Removes duplicate section from vulnerability management
- Adjust the image links so that they'll work in the web app itself as well as when reading the markdown on github. 
N.B. The solution for the images isn't ideal, because it'll always refer to the main branch, but after wrangling with other options (serving images as assets from the app in a location that relative URLs would work) for too long, this seems liked the sensible compromise for now.

Small documentation fixes

---

hq/app/logic/CredentialsReportDisplay.scala
hq/app/logic/VulnerableAccessKeys.scala
hq/app/model/models.scala
hq/app/schedule/IamDisableAccessKeys.scala
hq/app/schedule/IamFlaggedUsers.scala

This is a small change to centralise some access key rotation logic, which is now being shared by more than one report/job.
I also spotted a warning about duplicate code in one of the files I was changing, so the second commit adds a smaller conversion method to the model that avoids duplicated class creation code in the logic.

Centralise access key logic

---

cloudformation/watched-account.template.yaml

As it is not immediately obvious where the watched-account template is deployed, add a comment to explain it.
It is slightly easier to get started with this template.
No.
This is a no-op.

docs: Add a comment about where the StackSet lives

---

hq/app/views/fragments/credentialsHelp.scala.html

This updates the credentials helper dialog to include warnings about the newly-flagged "outdated key" statuses in the IAM creds report. It differs a bit from human to machine.
Help for people trying to understand why their IAM users are being flagged.
No
No

Update credential help dialog to include rotation errors

---

hq/app/logging/Cloudwatch.scala
hq/app/services/MetricService.scala

This PR improves the logging related to CloudWatch metrics:
1. When individual metrics are pushed successfully, we now log at `debug` (rather than `info`) level
2. When metrics cannot be pushed due to problems with data collection, we now log more details about what has gone wrong
1. Reduces [noise](https://logs.gutools.co.uk/goto/51d80808f26ebdf629c283e40c643be5), which should make it easier to analyse the logs
2. Helps us to debug in scenarios where [no metrics are being pushed (which seems to be the case at the time of writing!)](https://logs.gutools.co.uk/goto/4d189c03575774fcc3d9c44a6115a8f7)
No.

Improve logging for CloudWatch metrics service

---

hq/app/schedule/IamDisableAccessKeys.scala
hq/app/schedule/IamJob.scala
hq/app/schedule/IamMessages.scala
hq/app/schedule/IamRemovePassword.scala

This PR sends a notification email when Security HQ disables permanent IAM users (by removing the user's password and/or access key(s)). 
Here is an example of the email:
This aims to communicate to AWS account holders that there has been a change in the status of the IAM users in their account and how they can remediate this if required. 
By the time this email is sent, the AWS account holder should have received three emails warning them about the impeding automatic disablement and telling them how to avoid this.  In the case that SHQ fails to disable the user, it's important that DevX take responsibility for remediating this vulnerable user as the AWS account holder has not taken any action. 
I've added TODOs in the code to trigger a cloudwatch alarmso that DevX can debug this and …

Send notification when Credentials Reaper disables an access key or removes the password of a user

---

README.md

I realised when pairing with colleagues yesterday that it wasn't easy to find the google group that the reaper's test emails are sent to. I've added this detail to the documentation now along with an introduction to the reaper. I imagine that this can be added to in the future to make it easier for new developers to understand the reaper feature.

Adds documentation on reaper test google group

---

hq/markdown/vulnerability-management.md

This addition to the documentation explains the rules around managing permanent IAM credentials and explains what the Credentials Reaper does and how developers can avoid any unwanted disablements!

Documentation on managing IAM credentials & the Credentials Reaper

---

.gitignore
build.sbt
hq/app/schedule/Dynamo.scala
hq/test/schedule/DynamoTest.scala
project/plugins.sbt

Adds some basic Dynamo tests using the[ DynamoDB local](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html) jar provided by Amazon.  This jar (or rather the plugin that downloads it) provides a convenient way to run tests against an in-memory instance of DynamoDB. Unfortunately, it works by downloading the jar when the tests are run (unless it already exists) rather than as a classic project dependency. The [plugin project](https://github.com/localytics/sbt-dynamodb) also seems to be archived but it's quite simple so we could fork or recreate it. Other projects at the Guardian also already depend on it. On balance I would be willing to take the convenience over these downsides.
More confidence making changes to dynamo code (a little more)
No
I couldn't …

Add basic dynamo tests

---

hq/app/schedule/vulnerable/IamDisableAccessKeys.scala

This PR adds a failure case to the disable access key request so that a cloudwatch alarm can be triggered. 
This is valuable, because in the case that SHQ is unable to disable a vulnerable access key, the DevX team will be notified and they can take appropriate to action to understand what caused the failure, fix it or get in touch with the AWS account owner to disable the access key manually if required.

Failure case for disable access key request 

---

hq/app/logic/VulnerableAccessKeys.scala
hq/test/schedule/IamNotificationsTest.scala

This is a slight adjustment to the logic for determining flagged IAM users in the credentials reaper job. At the moment, even disabled keys will be flagged, but because the action on those keys is only to disable them, we would end up with circular logic until we actually implement key _deletion_.  We've decided to focus on the rollout of the reaper over deletion for now, so this change allows us to move ahead with a working system.
For now, we've duplicated some of the `isOutdated*` logic because we want to continue to flag in the UI that disabled keys should be removed.
Decouples the rollout of the reaper from implementing key deletion. We'd like to have confidence running the current version in production before adding deletion.
No
Paired on with @Nirvikalpa108 and @jorgeazevedo, …

Don't flag disabled keys in credentials reaper

---

hq/app/logic/CredentialsReportDisplay.scala
hq/app/logic/VulnerableAccessKeys.scala

Noticed that #299 missed a step to start using the newly duplicated methods for checking outdated status of keys. This fixes the dashboard to use the _old_ logic - that is to consider disabled keys as vulnerable.

Update references to outdated methods for the dashboard

---

hq/app/AppComponents.scala
hq/app/schedule/CronSchedules.scala
hq/app/schedule/Notifier.scala
hq/app/schedule/vulnerable/IamVulnerableUserJob.scala

This PR turns on the Credentials Reaper job for beta tester AWS accounts; frontend, mobile and deploy tools. This will be the first time that the reaper is in production with its ability to disable active access keys and remove passwords, so we're just testing it with a few accounts so as not to wreak havoc across the department!

Turn on the Credentials Reaper for beta testers

---

cloudformation/security-hq.template.yaml
hq/app/logging/Cloudwatch.scala
hq/app/schedule/vulnerable/IamDisableAccessKeys.scala
hq/app/schedule/vulnerable/IamRemovePassword.scala

This adds two cloudwatch metrics to track the operation of creds reaper. One tracks removal of passwords, the other disabling of keys. It uses a Dimension to track if the operation was successful or not
It also adds two cloudwatch alarms to email us when a failure happens. One for each type.
The alarm description contains a short URL to security hq's logs, which should contain the messages logged just before the `putMetric` methods are called.
https://logs.gutools.co.uk/s/devx/goto/f9915a6e4e94a000732d67026cea91be
Helps us track the execution of creds reaper and be alerted when it fails.
Yes! This requires an SNS topic passed as a parameter. I was hoping we had one already in the security account, but I think we'll have to create one.
Question: are SNS topics cloudformed? Are they just …

Add cloudwatch metrics and alerts to Creds Reaper

---

build.sbt
hq/app/schedule/unrecognised/IamUnrecognisedUserJob.scala

This PR creates a dummy Janus user using Janus's config library for 2 reasons.
First, so that the unrecognised former staff feature can use the library's built in methods for parsing a file as this feature intends to read a file from S3 which holds all of the users in Janus. The intention for this is to ensure that no IAM permanent credentials are assigned to anyone who is NOT included in Janus.
Second, the dummy user is being created so that we can concentrate on writing the main functionality of the feature comparing the Janus user name to names in IAM tags) and write the S3 file reading afterwards.

Create a dummy Janus user

---

hq/app/AppComponents.scala
hq/app/schedule/unrecognised/IamUnrecognisedUserJob.scala
hq/app/schedule/unrecognised/IamUnrecognisedUsers.scala
hq/test/schedule/IamUnrecognisedUserTest.scala

This adds logic to find all the latest human users who are not janus users. This means that these are the people with IAM permanent credentials who have left the Guardian. The next PR will be to disable these users' permanent credentials.

Find IAM users who are not Janus users

---

hq/test/schedule/SendTestNotifications.scala

A recent PR moved `disabledUsersSubject`, while another introduced a new usage of it but was branched from main before the merge of the first PR, and was not rebased. This caused compilation error on main post-merge of the latter.
Fix main build
No
No

Fix imports after merge

---

hq/app/schedule/vulnerable/IamDeadline.scala
hq/test/schedule/vulnerable/IamDeadlineTest.scala

This adds a couple of test cases for the `getNearestDeadline` method in `IamDeadline`. I was originally looking to update the tests for all of `IamDeadline` but spotted 2 edge cases with `getNearestDeadline` we might not be covering, which I think makes this worth its own PR. Hopefully the test cases are self-explanatory. They didn't pass without the accompanying changes.
- getNearestDeadline should ignore deadlines in the past(?)
- getNearestDeadline should return "today" when choosing between today and tomorrow
Potentially fixes some edge case bugs
No
Please verify the test cases are valid, and if you can think of any other meaningful cases to add for this method specifically.

Add test cases for edge case bugs in getNearestDeadline

---

hq/app/schedule/IamNotifications.scala
hq/app/schedule/IamUsersToDisable.scala
hq/app/schedule/vulnerable/IamDeadline.scala
hq/app/schedule/vulnerable/IamFlaggedUsers.scala
hq/app/schedule/vulnerable/IamVulnerableUserJob.scala
hq/test/schedule/IamNotificationsTest.scala
hq/test/schedule/IamUsersToDisableTest.scala
hq/test/schedule/SendTestNotifications.scala
hq/test/schedule/vulnerable/IamFlaggedUsersTest.scala

This is the second part of a closer look at the test coverage of the credentials reaper feature. With this PR I was targeting testing of the functionality that isolates users from the credentials report that are actually vulnerable. This logic is contained in `IamFlaggedUsers` and so I was looking at how to effectively test that class. In the end, both the tests and source code were changed in the following ways:
- `IamFlaggedUsers` and the tests were simplified a bit by moving a small piece of notifications logic. This leads to a return type including `VulnerableUser` rather than `IamAlertTargetGroup`. This is beneficial to isolate the notification types/logic from `IamFlaggedUsers`, and it'll mean we have decent test coverage of `IamFlaggedUsers` because that was the main untested part …

Creds reaper testing: finding flagged users

---

hq/test/schedule/IamUnrecognisedUserTest.scala

This raises the test coverage for the `IamUnrecognisedUsers` object to 100%, as having no tags is part of the pattern match in `filterUnrecognisedIamUsers`.
The behaviour for untagged users is an important part of the algorithm, so it's useful to have that expressed in the test. Namely, untagged users are left alone
No

Add user with no tags to users under test in IamUnrecognisedUsersTest

---

build.sbt
hq/app/services/CacheService.scala
hq/app/utils/Box.scala

This PR ports across a simplified version of https://github.com/guardian/box. 
This library was originally used to help teams to move away from akka Agents, but it is no longer worked on and is not published for more recent Scala versions. As the code that we need to keep is minimal, I think this copy+paste option is acceptable.
* Removes a dependency and unblocks Scala 2.13 upgrade
No

Port across functionality from Box

---

build.sbt
hq/app/AppComponents.scala
hq/app/api/Snyk.scala
hq/app/config/Config.scala
hq/app/model/models.scala
hq/app/services/CacheService.scala
hq/conf/application.conf

This PR removes the [configraun](https://github.com/guardian/configraun) dependency, as it is no longer maintained and is not published for Scala 2.13. 
I was originally planning to replace [configraun](https://github.com/guardian/configraun) with [simple-configuration](https://github.com/guardian/simple-configuration), but whilst researching this I noticed that we are only using this library to read 2 strings from parameter store anyway. All [other private config is currently fetched from S3](https://github.com/guardian/security-hq/blob/035c0f8de5d1a7a50b2b065d5d6878f1b779e09f/cloudformation/security-hq.template.yaml#L352) on startup.
The configraun dependency was originally introduced in https://github.com/guardian/security-hq/pull/64 with a view to migrating all config to parameter …

Remove configraun dependency and read Snyk config from file

---

hq/app/schedule/vulnerable/IamRemovePassword.scala

We've become aware that  `IamVulnerableUserJob` will always call `removePassword` for both human and machine users. Machine users do not have passwords, so the call will always fail for them.
This patch solves this by having `removePassword` filter out machine users from the list of users it receives.
The failure triggers a cloudwatch alarm, which doesn't really make sense in this instance!
No

Only attempt to remove passwords for human users

---

hq/app/views/index.scala.html
hq/public/javascripts/app.js
hq/public/stylesheets/main.css

The index page includes a list of all the AWS accounts monitored by Security HQ. This overview now exposes the account IDs.
We also add the ability to filter the full list of accounts (which is now quite large) by name or number. 
At the moment there isn't an easy way to lookup account by ID, so this page now exposes this value in the UI. In tools like AWS Security Hub, only the account ID is exposed (not our internal name for the account).
The filtering mechanism allows someone to investigate a security issue by filtering based on the AWS account ID.
No, this is a clientside-only change.
Screenshots of the behaviour are included below. The design changes at small sizes, to fit onto "mobile" sized devices.

Expose account numbers and allow account filtering

---

cloudformation/security-hq.template.yaml

Re: https://github.com/guardian/security-hq/pull/329 which has just merged.
At the moment Riffraff refuses to deploy because there are two ASGs with matching tags. This change temporarily changes tags for the old ASG to ensure Security HQ can be deployed while the CDK DNS changes are made and CDK cleanup.

Fix Riffraff deploy

---

hq/app/schedule/vulnerable/IamDisableAccessKeys.scala

The `disableAccessKeys` function used by the Unrecognised User job was only disabling outdated keys. This is a mistake! All keys should be disabled regardless of age, because the person will have left the company.
No.
No.

Unrecognised User job - access keys should be disabled regardless of age, when a colleague departs

---

cdk/lib/__snapshots__/security-hq.test.ts.snap
cdk/lib/security-hq.ts

(What it says.)
Required during CDK migration to reduce risk as we switch DNS to the new stack.

Drop TTL during migration

---

cdk/lib/__snapshots__/security-hq.test.ts.snap
cdk/lib/security-hq.ts

Reverts guardian/security-hq#339 as part (1) of the VPC-fix steps.

Revert "Update dns"

---

hq/conf/riff-raff.yaml

Note, the RR handling of this flag is quite brittle - as it fails the deploy if only a single matching stack is found.
Introduced by https://github.com/guardian/security-hq/pull/342, which (temporarily) removed the newer CDK ASG.

Remove migration flag as only one stack atm

---

cdk/.gitignore
cdk/README.md
cdk/bin/security-hq.ts
cdk/bin/security-vpc.ts
cdk/cdk.out/security-vpc.template.json
cdk/script/generate

Step **3** of the VPC fix. Follows:
* 1 https://github.com/guardian/security-hq/pull/341
* 2 https://github.com/guardian/security-hq/pull/342
* 3 <-- THIS PR
* 4 revert step number 2
* 5 revert step number 1
**NOTE: old VPC will need to be deleted manually first.**
Recreates VPC and makes synth for VPC manual.
This is required because the stack needs to be 'environment-aware'
to generate the right number of subnets and associated resources.
We don't have a way to provide credentials for this in CI (yet) so
need to do it manually for now.
https://docs.aws.amazon.com/cdk/latest/guide/environments.html
Corrects VPC setup.

Commit synthed template for VPC stack

---

cdk/lib/__snapshots__/security-hq.test.ts.snap
cdk/lib/security-hq.ts
hq/conf/riff-raff.yaml

Step **4** of the VPC fix. Follows:
* 1 https://github.com/guardian/security-hq/pull/341
* 2 https://github.com/guardian/security-hq/pull/342
* 3 https://github.com/guardian/security-hq/pull/343
* 4 <-- THIS PR
* 5 https://github.com/guardian/security-hq/pull/350
Reverts guardian/security-hq#342
TODO: Also adds some missing policies which are required for the SHQ tasks. Thanks @jorgeazevedo for reporting the errors here.

Revert "Removes CDK resources (temporarily)"

---

cdk/lib/__snapshots__/security-hq.test.ts.snap
cdk/lib/security-hq.ts

Step **5** of the VPC fix. Follows:
* 1 https://github.com/guardian/security-hq/pull/341
* 2 https://github.com/guardian/security-hq/pull/342
* 3 https://github.com/guardian/security-hq/pull/343
* 4 https://github.com/guardian/security-hq/pull/347
* 5 <-- THIS PR
A direct revert wasn't possible because of conflicts.

Revert dns change

---

hq/app/AppComponents.scala
hq/app/aws/AWS.scala
hq/app/aws/support/TrustedAdvisorS3.scala

This PR initialises s3Clients for all available aws regions, instead of just a single region, which defaulted to `US_EAST_1`.
`IamUnrecognisedUserJob.scala` relies on querying an s3 file, which is specified by bucket, key and region. The job fetches the client for the necessary region, and then calls `getObject`  
```scala
client <- s3Clients.get(config.securityAccount, config.janusUserBucketRegion)
s3Object <- getS3Object(client, config.janusUserBucket, config.janusDataFileKey)
```
Meanwhile, in `AppComponents` s3Clients is initialised to a single region, which defaults to `US_EAST_1`. This  is unlike `iamClients`, for example, which gets passed a list of regions to build clients for.
```scala
private val s3Clients = AWS.s3Clients(configuration)
private val iamClients = …
```

Initialise s3Clients for all available regions

---

hq/conf/riff-raff.yaml

Follows https://github.com/guardian/security-hq/pull/351 to fix the deploy - this flag currently fails the RR deploy as there are no longer 2 ASGs.
https://riffraff.gutools.co.uk/deployment/view/c4ee8bfa-4f48-46d1-98b8-a2f3babf5333

Remove migration flag

---

cdk/lib/security-hq.ts

Removes the tags import
eslint flags it as a warning and it shows up in every PR
Nope! This does not make a diff on the cloudformation yaml
Nope

Remove unused import from cdk

---

cdk/lib/__snapshots__/security-hq.test.ts.snap
cdk/lib/security-hq.ts

Add permissions to put metrics in cloudwatch
Allows sec hq to log data to cloudwatch
Yep!
No

Add permissions to put metrics in cloudwatch

---

cdk/lib/__snapshots__/security-hq.test.ts.snap
cdk/lib/security-hq.ts

This removes the custom SSM policy as the exact same policy is built-in to GuEc2App
No duplicate roles in IAM
Yes!
No!

Remove duplicate SSM policy included in GuEc2App

---

cdk/README.md
cdk/script/build
cdk/script/lint
cdk/script/test

This makes `build`, `lint` and `test` forward any argument passed to them to the underlying `yarn` call and updates the README accordingly.
Crucially, it mentions in the README that `./script/test -u` is how to update the snapshots, which always need to be ran when making changes to the cdk.
I didn't know how to update the snapshots! The easier solution would be to add `yarn test -u` to the documentation, but I saw an opportunity here to consolidate our cdk actions under the `script` interface, as it were. It's weird that everything else is done with these scripts, except this one important action.
One downside is that it's `--watch` instead of the more brief `-w`.
Another is that it's not standard. Even if we update the [upstream …

Make scripts generic and document `-u` 

---

cdk/lib/__snapshots__/security-hq.test.ts.snap
cdk/lib/security-hq.ts
hq/app/AppComponents.scala
hq/app/aws/s3/S3.scala
hq/app/config/Config.scala
hq/app/model/models.scala
hq/app/schedule/unrecognised/IamUnrecognisedUserJob.scala
hq/conf/application.conf

This addresses a couple of issues identified while testing the unrecognised user job in the dev-playground account.
- The instance did not have access to the S3 bucket containing the Janus data, that has now been added in a42b20b38856c63c0315ca39c996d47b5cb17d76
- The S3 client used to fetch the data was from the set of clients we use to monitor watched accounts. In this case, we are trying to perform an action specific to security-hq and the security account, so we have switched to using a specific S3 client for that. This allows the app to make a successful get-object request to the resource because the credentials chain is appropriate for the task. d551d1e5da3b27daa1a97fcaf0eba867041fec6e
Allows the job to perform its task by accessing S3
Yes, cdk updates included. I've already added …

Grant access for unrecognised user job to S3 bucket for Janus data

---

cdk/lib/__snapshots__/security-hq.test.ts.snap
cdk/lib/security-hq.ts
hq/app/AppComponents.scala
hq/app/aws/s3/S3.scala
hq/app/config/Config.scala
hq/app/model/models.scala
hq/app/schedule/unrecognised/IamUnrecognisedUserJob.scala
hq/conf/application.conf

Reverts guardian/security-hq#359
The parameter's default value uses Stage, which isn't available at this location. The actual error isn't super helpful for pointing at this, but we suspect it just means we get a `token` instead of a `String`, here.

Revert "Grant access for unrecognised user job to S3 bucket for Janus data"

---

hq/app/config/Config.scala
hq/app/logic/DateUtils.scala
hq/app/notifications/AnghammaradNotifications.scala
hq/app/services/IamRemediationService.scala

This PR adds the text for the notification messages that will be sent when an old credentials requires a warning, final and remediation notification.
SHQ sends notifications when a credential has been identified as requiring rotation so that developers are reminded to rotate the credential's access key(s). If this does not happen, SHQ will disable the credential and a notification will be sent once this has happened. This PR crafts the text for those notification messages.
No.
No.

Add Notification Message logic for iam-remediation

---

cdk/lib/__snapshots__/security-hq.test.ts.snap
cdk/lib/security-hq.ts
hq/app/AppComponents.scala
hq/app/aws/s3/S3.scala
hq/app/config/Config.scala
hq/app/model/models.scala
hq/app/schedule/unrecognised/IamUnrecognisedUserJob.scala
hq/conf/application.conf

Reverts guardian/security-hq#362 to enable the unrecognised user job. Includes a fix for the previous issue by avoiding a reference to `stage` in the cloudformation parameters.
There are other options (custom resources, [dynamic resolution](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html#dynamic-references-pattern)) for stage-specific parameters, but this is the simplest and achieves what we want.
Changes from the original implementation are in 96f251da33d70fab201f53a7c5c337ae0c3dfbab

Revert 362 revert 359 js/unrecognised user s3 access

---

.github/workflows/ci-sbt.yml
cdk/jest.setup.js
cdk/lib/__snapshots__/security-hq.test.ts.snap
cdk/lib/security-hq.ts
cdk/package.json
cdk/script/generate
cdk/yarn.lock

POC of using a Github [Deploy Key](https://docs.github.com/en/developers/overview/managing-deploy-keys) (really an SSH key) for read access to the @guardian/private-infrastructure-config repo.
Illustrate the concept before we decide whether to do further work.
The nice thing about Deploy Keys is that they provide read-only access to a specific repo. PATs, the alternative here, cannot be tightly scoped in this way.
Ultimately, the suggestion is we store the deploy key as an organisation secret but to test things here I've just added it as a repository secret.

POC to use private config repo via Deploy Key

---

hq/app/AppComponents.scala
hq/app/AppLoader.scala
hq/app/schedule/unrecognised/IamUnrecognisedUserJob.scala
hq/app/schedule/vulnerable/IamDisableAccessKeys.scala

This turns on the unrecognised user job for allowed accounts. The job checks all human IAM users against Janus credentials using a `GoogleUsername` tag. Any users for which the tag exists, but there is no Janus access linked to that username, will have their access keys and password disabled.
For now, the only configured allowed account in production is dev-playground.
Releasing the feature which will increase the likelihood that the IAM access of leavers is removed in a timely fashion.
No
Already made
While testing this, there were a couple of things to note that still haven't been addressed:
- The job is not entirely idempotent if run more regularly than the current schedule. This is because there is an assumption that the credentials report is up to date in identifying which users are …

Turn on unrecognised user job for allowed accounts

---

hq/app/logic/IamRemediation.scala
hq/app/services/IamRemediationService.scala
hq/test/logic/IamRemediationTest.scala

This takes a list of RemedationOperations and splits it in 2, according to list of accounts we are allowed to perform remediation operations in
No
No

Implement IamRemediation/partitionOperationsByAllowedAccounts

---

hq/app/logic/IamRemediation.scala
hq/test/logic/IamRemediationTest.scala

This implements `formatRemediationOperation`, which is called by `dummyOperation` to log what it would have done. In context, dummyOperation will produce 2 logs lines that look like this
```
Remediation operation skipped because testAccountId is not configured for remediation
Skipping remediation action: OutdatedCredential FinalWarning for user machine.user from account testAccountId
```
No
No
Depending on the purpose of the `dummyOperation` log this might be insufficient. For example, it doesn't say which key it's referring to, and doesn't shed any light on why it's doing this particular operation.

Implement formatRemediationOperation

---

hq/app/config/Config.scala
hq/app/logic/IamRemediation.scala
hq/test/logic/IamRemediationTest.scala

Adds tests and implementations for the logic required by the IAM Remediation job to determine which operations, if any,
are required for old credentials.
Determines which work SHQ should do on vulnerable access keys.
No.
I have made some changes to the alert cadence and I would like to check that everyone in the team is happy with this. 
Also, I want to check what we would like to do in the case that an access key is enabled, vulnerable and its most recent operation type is `Remediation`. 
Ideally this case should never happen because all vulnerable credentials would be disabled if denoted as ready for Remediation, but in the case that it does I suggest the key is flagged for remediation again so that SHQ can attempt to disable it again in case something has gone wrong with the automated …

IAM Remediation: calculateOutstandingOperations

---

hq/app/logic/IamRemediation.scala
hq/test/logic/IamRemediationTest.scala

Adds implementation for the lookupCredentialId function.
This function attempts to find matching access key metadata from an AWS list-access-keys API call, with the problem access key that SHQ has identified.
If this fails, a FailedAttempt is returned, because this means that the access key cannot be disabled as an access key id has not been identified.
No love.
No.
This change includes an important edge case.
Currently we differentiate access keys by date, but what if both a user's access keys were created on exactly the same date to the second?
Yes, this is unlikely, but an edge case nevertheless. I think this would be impossible if the keys were created in the console, but could potentially be possible if the CLI were used.
This has been accounted for by returning a FailedAttempt and …

IAM remediation lookupCredentialId implementation

---

cdk/lib/__snapshots__/security-hq.test.ts.snap
cdk/lib/security-hq.ts
hq/app/schedule/unrecognised/IamUnrecognisedUserJob.scala

On testing of the unrecognised user notification in production, 2 things became apparent:
1) The notification was not being sent. The logs indicated an attempt was made by the program to put a message on the necessary Anghammarad SNS topic, but the lambda was not invoked, indicating the topic was not published to.
2) There was no indication in the SHQ logs that this failure happened.
To address these this PR does the following:
1) Adds the necessary Anghammarad SNS publish policy to the instance role via CDK. It looks like this was omitted when we migrated to CDK, but it wasn't important until now.
2) Updates the error handling in the part of the job that interprets the result of a notification `send`. We were previously `fold`ing an `Attempt` (to a `Future`) and then transforming back to …

Unrecognised user notification handling improvements

---

project/plugins.sbt

Updates to the latest version of the riffraff artifact plugin, which avoids making a network request (and generating a warning) on sbt startup.
Avoids unnecessary network request and warning on sbt startup.
No
No
No

Update riffraff artifact plugin to avoid warning on sbt startup

---

.github/workflows/ci-sbt.yml

Use the new https://github.com/guardian/actions-read-private-repos action to simplify private repo access in the Github actions CI workflow.

Use new action to simplify workflow

---

cdk/lib/__snapshots__/security-hq.test.ts.snap
cdk/lib/security-hq.ts

The refactor of the outdated credentials job has changed the database structure. It now includes a range key as well as a primary key, which this PR adds.
The database is now up to date with the refactored IAM remediation job.
Yes. 
No.
Before this PR is deployed, the current db table should be deleted. This should be safe as the data in it has only been used for test purposes only and it's not a problem if we send another email about the same credential if one has already been sent in the past.

Update DB schema for IAM Remediation jobs

---

hq/app/db/IamRemediationDb.scala
hq/test/db/IamRemediationDbTest.scala

This implements the outstanding methods in IamRemediationDb, namely
- lookupIamUserNotifications
- writeRemediationActivity
- lookupScanRequest
- writePutRequest
- deserialiseIamRemediationActivity
- scan
No
No
- method signatures were changed to include ExecutionContext when using attempts and for comps
- the suite of helped methods such as `S` and `L` were moved to the companion object, so they could be used both in the tests and across the implementation

IamRemediationDb implementation

---

.gitignore
README.md
build.sbt
hq/app/AppComponents.scala
hq/app/aws/AWS.scala
script/setup

This PR makes security hq's dynamo db client connect to `localhost:8000` instead of aws when running locally. To that effect this PR patches the sbt configuration to have `DynamoDbLocal` automatically started, and introduces an initialisation script for the database table and the directory that will hold it between applications runs.
No
No

Use DynamoDbLocal for local application development

---

build.sbt
hq/app/auth/SecurityHQAuthActions.scala
hq/app/controllers/AuthController.scala
project/build.properties
project/plugins.sbt

Due to the log4j exploit, this PR upgrades sbt to 1.5.7 where log4j has been updated to a safe version. 
This means that it should not be possible for SHQ to be compromised using log4j in sbt. This possibility is very much an edge case, but this change seems prudent nevertheless.
No.
No.
The sbt upgrade also required a play upgrade, which triggered binary incompatibility warnings with scala-java8-compat. This has been fixed using a `libraryDependencySchemes` setting as described here: https://github.com/guardian/status-app/pull/94/files/23687b0a44a0b0ad3afad39a19d903b4b22e6160#diff-5634c415cd8c8504fdb973a3ed092300b43c4b8fc1e184f7249eb29a55511f91R17.

Upgrade SBT to 1.5.7 to protect from log4j exploit

---

hq/app/schedule/vulnerable/IamRemovePassword.scala

This adds error recovery during attempts to remove a login profile (i.e. password) from an IAM user. Currently we handle errors from AWS by transforming them into more helpful `FailedAttempt` types, but generally there hasn't yet been a need to recover from an error by treating it as a successful attempt. However, we don't actually care if a password we try to remove no longer exists (very possible due to the current 4 hour lag in source data from the credentials report), so in this instance we treat it as a success.
If the jobs that utilise this feature are run more frequently, they will not fail when attempting to remove passwords multiple times.
No
No
If interested, there were alternative, more generic, approaches explored in #381 and #382. Since we're only needing to do error recovery …

Treat missing login profile as successful password removal

---

hq/app/logic/IamRemediation.scala
hq/app/services/IamRemediationService.scala
hq/test/logic/IamRemediationTest.scala

Adds the outline for a new remediation job that will remove passwords where there is no associated MFA. This follows the same pattern as the reworked "Outdated Credentials" job, so we can re-use a lot from there. The remaining work in filling out this job has been added as tasks to trello.
Starts work to implement the second remediation job in the new structure.
No
No
This job (and the outdated credentials one) are not yet called/run from anywhere

Outline "Password no MFA" job

---

hq/app/logic/IamRemediation.scala
hq/app/services/IamRemediationService.scala
hq/test/logic/IamRemediationTest.scala

Adds an implementation and tests for the method we use to identify human users (those with passwords) but with no MFA enabled.
Starts filling in the implementation of a job to disable users who have a password without MFA enabled
No
No
No

Identify human users without MFA

---

hq/app/AppComponents.scala
hq/app/config/Config.scala
hq/app/db/IamRemediationDb.scala
hq/app/logic/IamRemediation.scala
hq/app/services/IamRemediationService.scala
hq/conf/application.conf
hq/test/logic/IamRemediationTest.scala

This PR adds scheduling and instantiates the `IamRemediationService` so that it will be triggered when the app starts and will run every 5 hours.
In addition, it adds an additional config property; a list of AWS account Ids for which the remediation service is run on. Also, this PR changes the cadence of the remediation service, so that it can be tested more easily. 
The additional config value means that the feature can be rolled out more incrementally, because not all accounts are ready for this service to be turned on.
No.
Yes! Here is the new config property, `ACCOUNT_IDS_FOR_IAM_REMEDIATION_SERVICE`, which is a list of AWS Account Ids.
Here is the rollout plan:
1. Add Deploy Tools and Domains to the list of account Ids in config
2. Deploy this branch to PROD and check that the …

Schedule and instantiate IamRemediationService

---

hq/app/aws/s3/S3.scala
hq/app/aws/support/TrustedAdvisorS3.scala

This attempts to use an AWS S3 client with the region provided by the Trusted Advisor report. We are only using `US-EAST-1` for all S3 requests, which meant that any buckets outside that region would be assumed to have no encryption (even though they might).
You can see this with the following bucket which has default encryption turned on and is in `EU-WEST-1`:
As it turns out, there also appears to be a limitation with the regions provided by Trusted Advisor - they don't seem to be provided unless the bucket is public, so this change will not fix that. I've opened a support ticket to find out more.
The S3 report should more often show the correct default encryption status for buckets outside `US-EAST-1`. As it happens, for buckets in `US-EAST-1` whose region is not provided by Trusted …

Use region provided by trusted advisor for S3 client to check encryption status

---

.gitignore

Adds the `.bsp` directory to the gitignore file. This is a directory used by the build server protocol, adopted in sbt 1.4.0 which we recently updated to.
Ref: https://www.scala-lang.org/blog/2020/10/27/bsp-in-sbt.html

Add build server protocol directory to gitignore

---

hq/app/logic/IamRemediation.scala
hq/app/notifications/AnghammaradNotifications.scala
hq/test/logic/IamRemediationTest.scala

Adds a few small bug fixes to the outdated credentials job which we have been testing in the `Domains` account. Namely:
- (Main fix) the `problemCreationDate` is correctly initialised to the last rotated date of the vulnerable access key, rather than the time the job ran, which will correct both the notification message and importantly allow the job to find previous warnings
- Simplifies the filtering of the activity history and removes the day-level-granularity comparison, preferring exact equality. This should prevent mix ups between keys created on the same day.
- Small correction to the rectification date on the initial warning email
- Adjusts the conditions for when a final warning or remediation should be performed, giving at least a day's grace between stages of remediation (unless …

Outdated credentials job bug fixes

---

hq/app/services/IamRemediationService.scala

Updates the scheduling of the outdated credentials job, in 2 ways:
- Adds an explicit initial delay of 10 minutes, giving the cache service time to populate the credentials report we require for this job. We could also introduce a dependency on the cache service `Observable`, but I've left that for later. Right now the initial delay is implicitly set to 5 hours, making it hard to observe changes we deploy to the job.
- Restricts execution of the job to working hours, as it may take dangerous actions in accounts if warnings are not heeded.
Job runs at times that are easier for us to observe, and at times where teams can respond to actions taken by it (even if that's just a warning email).
No
No
No

Schedule the outdated job during working hours and allow cache to populate

---

hq/app/notifications/AnghammaradNotifications.scala

Adds "...at the next opportunity" to the end of the notification messages to indicate that the remediation may not happen on that day, because the job doesn't run at the weekend currently. I've kept it generic sounding so we don't have to worry too much about changing the scheduling and keeping this message up to date.
Also removes an extra quote from the messages.

Clarify remediation date in notification and remove extra quotes

---

hq/app/services/IamRemediationService.scala

Updates the outdated credentials job to run only twice per day, spaced at least 4 hours apart. This is primarily to resolve an issue where duplicate notifications/disables are actioned when a `Remediation` action has already been taken, but the credentials report hasn't yet updated (i.e. it hasn't been longer than 4 hours.) That can happen at the moment if we deploy during that 4 hour window, because the job(s) run shortly after the app starts.
We also considered alternate solutions that solved the root cause, rather than changing the schedule, but the way the code is currently structured makes it relatively complicated to do so. We could revisit this later.
Avoids duplicate actions in the job
No
No
No

Only run the outdated credentials job twice per day

---

hq/app/config/Config.scala

Now that we have tested the outdated credentials job in a few accounts, we can revert the grace period between `first -> final warning`, and between `final warning -> remediation` back to the originally intended 7 days.
More user-friendly deadline for making changes after a warning.
No
No
No

Revert to 7 day grace period between warnings, post testing

---

hq/app/config/Config.scala
hq/app/logic/IamRemediation.scala
hq/test/logic/IamRemediationTest.scala

Adds a tag that can be applied to IAM users which will opt them out of identification by the Outdated Credentials job. This is to deal with the (thankfully rare) scenario where an account contains a key that cannot simply be rotated e.g. it is embedded in a large number of places. This opt-out tag would allow us to enable the job on those accounts even while the team is working on rotating it. *It should be a last resort only*
The upside to this approach is that when we are able to rotate the user, all that needs to be done is to remove the tag. The downside is that this is a publicly visible key that can be used to bypass a useful security measure. If it is abused then we won't be alerted immediately, but we will start to see keys in the dashboard over 365 days old in accounts where the …

Create per-user opt-out for Outdated Credentials job

---

cdk/lib/__snapshots__/security-hq.test.ts.snap
cdk/package.json
cdk/yarn.lock

Bumps the version of aws cdk to the most recent one.
The latest revision of the ec2 pattern includes permission to access SSM parameters which will make implementing play secret rotation, and therefore upgrading `com.gu.play-googleauth` to the most recent version, easier.
Nope
Also nope

Update cdk to the latest version

---

.github/workflows/snyk.yml

This rewrites our snyk workflow to use the new guardian org level snyk workflow rather than a custom implementation, which is in line with our current guidelines but actually doesn't work for us.
Testing this new global snyk workflow, which has the potential to be adopted widely across the department.
Finally having reliable data about which dependencies the project uses.

Switch to guardian org snyk workflow

---

build.sbt
hq/app/AppComponents.scala
hq/app/auth/SecurityHQAuthActions.scala
hq/app/aws/AWS.scala
hq/app/config/Config.scala

Updates the version of play google auth we're using to `2.2.2` which introduces play secret rotation for the first time. To begin with this will use a static secret from SSM, and later we can introduce a rotation strategy.
This work is a precursor to moving to scala 2.13 and to addressing some vulnerabilities identified by snyk.
No
Yes, I've already added DEV and PROD secrets to SSM.
No

Update Play Google Auth

---

.github/workflows/ci-sbt.yml
README.md
build.sbt
hq/conf/riff-raff.yaml

Updates to Java 11, which the Guardian's Play Secret Rotation library ultimately depends on (via https://github.com/guardian/play-secret-rotation/blob/main/build.sbt#L18) on https://github.com/ben-manes/caffeine/releases/tag/v3.0.0.

Move to Java 11

---

.github/workflows/ci-sbt.yml

We developed https://github.com/guardian/actions-assume-aws-role to support the migration to GitHub Actions (more specifically, it allowed us to upload build artifacts to Riff-Raff's S3 buckets without using permanent credentials).
There is now an official action (maintained by AWS) which offers this functionality - https://github.com/aws-actions/configure-aws-credentials. This PR switches to using the AWS alternative instead of the (now deprecated) Guardian action. 
Related PRs:
https://github.com/guardian/actions-assume-aws-role/pull/80
https://github.com/guardian/node-riffraff-artifact/pull/33
https://github.com/guardian/sbt-riffraff-artifact/pull/69

Use aws-actions/configure-aws-credentials instead of guardian/actions-assume-aws-role

---

hq/app/aws/s3/S3.scala
hq/app/aws/support/TrustedAdvisorS3.scala
hq/app/model/models.scala

We currently have an issue when S3 buckets that are listed in the Trusted Advisor report (which is refreshed by AWS very infrequently) are subsequently deleted. This means for an account where a bucket is removed, we stop processing results and return an error for the entire account:
With this change we are instead recovering from `BucketNotFound` errors and simply removing those buckets from the account's list, which seems most appropriate in this situation.
(Note the lack of error)
Removes the occasional error from the dashboard when a bucket is deleted in an account, and it should mean our metric shipping is more stable, as _any_ error meant those weren't sent (which probably needs revisiting separately)
No
No
No

Remove "not found" buckets from S3 report

---

hq/app/aws/iam/IAMClient.scala
hq/app/logging/Cloudwatch.scala
hq/app/logic/CredentialsReportDisplay.scala
hq/app/logic/IamListAccessKeys.scala
hq/app/logic/IamUnrecognisedUsers.scala
hq/app/services/IamRemediationService.scala

This refactor aims to address some inconsistencies and duplication in the functionality that removes passwords and disables access keys in AWS IAM. Namely:
- Disabling of access keys was done in 2 places
- Password removals were not using the IamClient at all
- Existing methods had inconsistent signatures
We aim for the IamClient to be a fairly thin wrapper around the AWS SDK, with the application specifics of how those are used housed elsewhere. We could probably go further than this does, but that can come later and is less justified anyway.
There were a couple of other minor changes included, like removing a bit more unrelated duplication, and some moving of methods.
Clearer separation of application logic from AWS SDK interaction and less duplication of functionality.
No
No
I'll need …

Refactor use (and lack of use) of IamClient for consistency

---

build.sbt
hq/test/aws/AWSTest.scala
hq/test/aws/cloudformation/CloudFormationTest.scala
hq/test/aws/ec2/EC2Test.scala
hq/test/aws/ec2/EFSTest.scala
hq/test/aws/iam/CredentialsReportTest.scala
hq/test/aws/support/TrustedAdvisorExposedIAMKeysTest.scala
hq/test/aws/support/TrustedAdvisorRDSSGsTest.scala
hq/test/aws/support/TrustedAdvisorSGOpenPortsTest.scala
hq/test/aws/support/TrustedAdvisorTest.scala
hq/test/db/IamRemediationDbTest.scala
hq/test/logic/CredentialsReportDisplayTest.scala
hq/test/logic/DateUtilsTest.scala
hq/test/logic/DocumentUtilTest.scala
hq/test/logic/IamOutdatedCredentialsTest.scala
hq/test/logic/PublicBucketsDisplayTest.scala
hq/test/logic/RetryTest.scala
hq/test/logic/SecurityGroupDisplayTest.scala
hq/test/logic/SnykDisplayTest.scala
hq/test/logic/VulnerableAccessKeysTest.scala
hq/test/model/TagTest.scala
hq/test/schedule/unrecognised/IamUnrecognisedUsersTest.scala
hq/test/utils/attempt/AttemptTest.scala
hq/test/utils/attempt/AttemptValues.scala
lambda/common/src/test/scala/com/gu/hq/lambda/JsonParsingTest.scala
lambda/common/src/test/scala/com/gu/hq/lambda/model/JSONTest.scala
lambda/security-groups/src/test/scala/com/gu/hq/EventsTest.scala
lambda/security-groups/src/test/scala/com/gu/hq/NotifierTest.scala
lambda/security-groups/src/test/scala/com/gu/hq/SecurityGroupsTest.scala

Upgrades the testing-related dependencies that are currently on versions that were not built for scala 2.13.
This is not a trivial change, mainly due to the movement of entities in scalatest 3.1.0 described here: https://www.scalatest.org/release_notes/3.1.0.
I have split it into 3 commits:
1. Bump the existing dependencies in 673df1a9a7bad489822f0b8b752efa80cb07bed7
2. Autofix the renames/moves using [this procedure](https://github.com/scalatest/autofix/tree/master/3.1.x) in d4a1585fe98ddddebe51c880af07215ada2a174c. As this was automated, it can be largely ignored for review purposes.
3. Introduce scalatestplus scalacheck in 62e45598feae1423b802bc93de5d809f977737a6, which is the new separate library for combining scalatest and scalacheck. Previously this functionality was in scalatest …

Upgrade test dependencies for scala 2.13 compatibility

---

build.sbt
project/plugins.sbt

Updates our versions of scala-csv, anghammard and Rxscala to the latest which have 2.13 compatibility. This will prepare us for moving to scala 2.13.
N.B. Rxscala is EOL, however they claim to still be committed to releases for bugs and new language versions. I think it's still worth moving off, but it's a separate concern to moving to scala 2.13.

Simple upgrades of dependencies for scala 2.13 compat

---

hq/app/api/Snyk.scala
hq/app/config/Config.scala
hq/app/controllers/SnykController.scala
hq/app/logic/SnykDisplay.scala
hq/app/model/Serializers.scala
hq/app/model/models.scala
hq/app/services/CacheService.scala
hq/app/utils/attempt/Failure.scala
hq/app/views/snyk/snyk.scala.html
hq/app/views/snyk/snykOrgProjects.scala.html
hq/public/stylesheets/main.css
hq/test/logic/SnykDisplayTest.scala
hq/test/resources/logic/SnykDisplayTestResources/goodAndNotVulnerableResponse.json
hq/test/resources/logic/SnykDisplayTestResources/goodButVulnerableResponse.json

This PR restores the previously disabled Snyk dashboard. The main motivation for this is to experiment with introducing an SLO for 3rd party vulnerabilities, which requires providing relevant metrics to users.  This PR implements a basic warning in that area that an organisation contains long-lived high/critical severity vulnerabilities.
We have deviated significantly from the previous functionality/API usage.  Previously we would work on a per-project basis and make API calls for each of those (all 400+ 😱 ). Now we are utilising the reporting API at the organisation level (i.e. per team) to gather the information we need, which makes the density of requests much more manageable.
There are certainly improvements to be made still, but this PR is already large. Namely we could:
- Surface …

Restore/revamp Snyk dashboard with vulnerability age indicator

---

cdk/script/ci

This disables network concurrency during the `yarn install` step of the cdk cli script
I tried a bunch of work arounds mentioned in the corresponding yarn issues, but this was the one I found worked
* https://github.com/yarnpkg/yarn/issues/6312
* https://github.com/yarnpkg/yarn/issues/2629
Fixing builds
No
No

Workaround for CI build failing

---

build.sbt

Updates google-cloud-securitycenter to the latest version. There was only one breaking change since our last update and it doesn't seem relevant to us.

Update google-cloud-securitycenter to 2.5.1

---

cdk/package.json
cdk/yarn.lock

Removes some migration dependencies from the cdk project. These are no longer needed and the size of them (mainly `cloudformation-include` is causing a much slower build than necessary.
Faster builds, less unnecessary dependencies
Should be no changes to the output of the CDK project
No
No

Remove unneeded CDK migration dependencies

---

.github/workflows/snyk-pr.yml
build.sbt

This workflow uses the new snyk PR workflow (see https://github.com/guardian/.github/tree/ja-snyk-pr) to test PRs that change dependencies for new vulnerabilities.
Preventing vulnerabilities from being committed to main!
No
No

Add workflow to test PRs for new vulnerabilities

---

.github/workflows/ci-sbt.yml
README.md
script/ci

With this patch, the ci workflow only uploads builds to riff raff (and, more importantly, only has _permissions_ to upload) on PRs opened by devs. For PRs opened by dependabot, the riff raff steps are skipped.
This will make builds for dependabot PRs green. They currently fail because they do not have access to the necessary permissions. This is due to a security measure implemented by github on march 2021, where the ci build environment offered to dependabot no longer has access to secrets to prevent malicious dependencies from syphoning them off or using them as an attack vector. See https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-852541544
No
No

Skip riff raff upload on dependabot PRs

---

hq/app/notifications/AnghammaradNotifications.scala

Updates the subject of the vulnerable credential email from:
```
Action required: vulnerable credential in Media Service will be disabled soon
```
to:
```
Action required by 25/12/2022: vulnerable credential in Media Service will be disabled soon
```
This is an effort to draw more attention to the deadline as the email body doesn't have formatting (e.g. bolded text).
Hopefully, it is easier to understand deadline days.
No.
No.
No.

Add credential expiry date to email subject

---

cdk/package.json
cdk/script/ci
cdk/yarn.lock

We introduced a workaround for CI instability in #433 which we believe was caused by yarn's handling of `prepare` scripts. We've now moved the `private-infrastructure-config` repo to adopt a different method (doing `tsc` in a pre-commit hook.)
Removes workaround for clearer, idiomatic CI scripting and should improve build speed
No
No
I'm not planning to do a full rigorous test of this change, with yarn cache purging and multiple pushes. If there continues to be problems they will become apparent and it will be a simple revert to fix.

Remove CI stability workaround

---

hq/markdown/snyk.md

Depends on: https://github.com/guardian/.github/pull/17
Links through to the docs that are closer to the code to avoid staleness. A consideration is that you have to go between links when reading, but what's the internet if not a set of links.
This change has been made in response of wanting to use the new actions and this documentation being out of date.
Helps stop this documentation going stale when code changes are made in another repo.
Nope
Nope
Nope

add link to snyk github actions

---

.github/workflows/ci-sbt.yml
.github/workflows/dep-updates_pr-tracking-branch-to-default.yml
.github/workflows/dep-updates_set-automerge.yml
.github/workflows/dep-updates_tracking-branch.yml

Adds a workflow for managing automatic dependency updates (e.g. via Scala Steward). Allows multiple PRs to be batched together for less overhead during manual review/merge.

chore: Add dependency update workflows

---

.github/PULL_REQUEST_TEMPLATE.md

Supersedes https://github.com/guardian/security-hq/pull/451 to remove git.io references after its deprecation. The original PR was assumed to be failing due to being from a fork (without build logs I can't investigate that so this is simpler)

fix: resolve git.io url

---

.github/workflows/ci-sbt.yml

Re-enables CI on the `dependency-updates` branch in order to try out a workflow that requires CI to complete successfully before update PRs are merged.

Try dependency update workflow including granular CI

---

hq/app/logging/LogConfig.scala

Fixes remote log shipping via the kinesis logback appender.
Log shipping via kinesis was updated to use AWS SDK v2 (via the kinesis logback appender v2), but that included a change in the SDK that validated the existence of an STS client when `.setRoleToAssumeArn(role)` is called. This setter is unnecessary, as `setCredentialsProvider` is preferred for our usage, which appears to now be (strictly) mutually exclusive.
Verified locally.
The exception encountered was:
```
java.lang.NullPointerException: STS client must not be null.
at software.amazon.awssdk.utils.Validate.notNull(Validate.java:119)
at software.amazon.awssdk.services.sts.auth.StsCredentialsProvider.<init>(StsCredentialsProvider.java:70)
at software.amazon.awssdk.services.sts.auth.StsAssumeRoleCredentialsProvider.<init>(StsAssu …
```

Fix log shipping - avoid unnecessary setter usage

---

.github/dependabot.yml

Adds dependabot configuration for dependency updates that target the `dependency-updates` branch. We use this branch to batch together multiple updates for ease of review/test.
Dependabot updates are easier to manage.

Configure dependabot to target non-default branch

---

.scala-steward.conf

Scala steward will now only create a PR every 30 days or so
To reduce noise/admin tasks

update only every 30 days

---

build.sbt

Play 2.8.17 is compatible with logback 1.3+, so in theory removing this restriction means next month both dependencies will be bumped and everything will work.

Remove restriction on scala-steward logback updates

---

build.sbt

This follows out own advice and upgrade to 2.13.10 to avoid the vulnerability:
https://www.cve.org/CVERecord?id=CVE-2022-36944

Upgrade Scala version to 2.13.10

---

hq/app/controllers/SnykController.scala
hq/app/services/CacheService.scala
hq/app/views/snyk/snykOrg.scala.html
hq/conf/routes

This change adds a `snykOrg` view and controller function that allows requests to `/snyk/:snykOrk` to be routed to individual organisation pages.
The motivation for this change is to allow teams to be given links to their own page on Security HQ to provide a more focussed view of their issues.
No
No.
There is no route from from the `/snyk` page to the `/snyk/:snykOrg` page, there should probably be one but it doesn't have to be in this PR and doesn't prevent handing a link to an org/team page out now.

Make Snyk reports by team individually addressable.

---

.gitignore
hq/app/logging/Cloudwatch.scala
hq/app/logic/GcpDisplay.scala
hq/app/model/models.scala
hq/app/views/gcp/gcp.scala.html
hq/test/logic/GcpDisplayTest.scala

Currently GCP projects are displayed ordered alphabetically. While this is useful to quickly identify known projects it doesn't provide an easy way to prioritise remediation effort. The change implements GCP project sorting by number of vulnerabilities and their criticalities.  The projects with higher number of findings with higher criticality will be displayed at the top of the list.
It would be easier for reviewers to focus their remediation effort.
No
No
No CSS and JS changes

Display gcp projects sorted by findings criticality

---

hq/app/api/Snyk.scala

A Snyk severity level is defined as:
> A severity level is applied to a vulnerability, to indicate the risk for that vulnerability in an application.
>   – https://docs.snyk.io/features/fixing-and-prioritizing-issues/issue-management/severity-levels
A Snyk priority score is defined as:
> Snyk created a Priority Score to make the prioritization of issues as quick and easy as possible, ensuring the highest-risk issues have the highest score.
> – https://docs.snyk.io/features/fixing-and-prioritizing-issues/issue-management/priority-score
The priority score is calculated using a number of signals including:
- severity levels
- exploit maturity
- reachability
- fixability
- time
- social trends
- malicious packages
That is the severity level could be considered a subset of the priority score, …

fix(snyk): Only show issues for active projects on the dashboard

---

hq/conf/riff-raff.yaml

Updates `riff-raff.yaml` to resolve a warning message seen during deployment.
See https://github.com/guardian/riff-raff/pull/884.

chore: Resolve Riff-Raff warning

---

.github/workflows/snyk.yml

Removes the Snyk schedule, which is unnecessary and will cause the workflow to become suspended after 60 days of inactivity on the repo!

ci: Remove unnecessary Snyk schedule

---

sbt
script/start

Updates the start script to forward flags to the sbt script, allowing you to run `./script/start --debug`, for example.
Also removes some redundant TeamCity based logic as we've moved to GitHub Actions for CI.

chore: Update local running DX

---

.tool-versions
cdk/lib/__snapshots__/security-hq.test.ts.snap
cdk/lib/security-hq.ts
cdk/yarn.lock
hq/app/auth/SecurityHQAuthActions.scala
hq/app/config/Config.scala
hq/conf/application.conf

This PR adds authentication to the ALB and also adds a second group check to the application code, following the approach taken in other tools to restore access to the tooling for the department at large.
In addition the PR:
- Updates the CDK packages
- Adds nodejs version to the tools-versions file
- Adds the `public.` prefix to the domain
This PR addresses the work needed to enable access to security HQ again. A further change is required to allow access to the world.

Add ALB authentication and group check

---

cdk/lib/__snapshots__/security-hq.test.ts.snap
cdk/lib/security-hq.ts

Now #775 is merged and tested this makes the follow up change to make the service available to everyone again.
People will again be able to analyse the security of their AWS accounts and other resources.

Make security-hq available to the whole internet

---

hq/markdown/vulnerability-management.md

Updated security report links
The links are no longer broken (point to public resources)
no
no
no

Updated the new public URLs for security reports

---

cdk/lib/__snapshots__/security-hq.test.ts.snap
cdk/lib/security-hq.ts

This PR adds the ALB's ARN to parameter store so that it can be used/looked up by `cdk` stacks in https://github.com/guardian/waf. 
See https://trello.com/c/Gf4wbq5Y/1716-configure-wafs-for-all-services-in-their-own-repository
[Deploy to `PROD`](https://public.riffraff.gutools.co.uk/deployment/view/2a24091f-5c76-4350-bb08-27d38b691575) to confirm that the parameter is created as expected.
This allows us to move forwards with the work to define a separate WAF for AMIgo via a different repository.

Create SSM parameter with ALB arn (for WAF configuration)

---

cdk/lib/__snapshots__/security-hq.test.ts.snap
cdk/lib/security-hq.ts

In this change we create the CNAME of `security-hq.gutools.co.uk` pointing to the same ALB as `public.security-hq.gutools.co.uk`.
This is part of an effort to restore pre-incident URLs[^1], whilst also maintaining any changes implemented during the incident (i.e. WAF).
This change also sets the subject alternative name of the TLS certificate that is served by the ALB.
Once this is merged, SHQ will be accessible via both `public.security-hq.gutools.co.uk` and `security-hq.gutools.co.uk`.
Yes. See CDK snapshot update for exact changes.
N/A.
None.
[^1]: We've spotted a number of cross linking between apps break because they reference the pre-incident URL. Rather than update them, we think restoring these URLs offer a better DX.

Add `security-hq.gutools.co.uk` CNAME

---

hq/markdown/vulnerability-management.md

Reverts guardian/security-hq#783 as we're restoring the previous URLs.

Revert "Updated the new public URLs for security reports"

---

.github/dependabot.yml
.github/workflows/ci-sbt.yml
README.md
script/ci

In #445 and #552 we configured Dependabot to run weekly, and bundle changes into the `dependency-updates` branch, which gets PR'd against `main` once a month.
Whilst this process has been working, there are a couple of drawbacks:
- The repository is set up differently from all other repositories
- The revision history of the `dependency-updates` branch is [quite noisy](https://github.com/guardian/security-hq/pull/816), as Scala Steward is also adding commits
- A single branch makes it difficult to isolate infrastructure changes from application changes
In this change, we configure Dependabot in the same way as other repositories:
- Run once a month
- Raise PRs against `main`, one PR per dependency bump
The downside of this is we loose the Riff-Raff upload protections that #445 added, but …

Remove Dependabot from `dependency-updates` process

---

cdk/lib/__snapshots__/security-hq.test.ts.snap
cdk/lib/security-hq.ts

> **Note**
> Only to be merged once comms have been sent.
Removes access to SHQ on the domain `public.security-hq.gutools.co.uk` as we've reverted back to `security-hq.gutools.co.uk`.
The removed resources include:
- The 301 redirect from `public.security-hq.gutools.co.uk` to `security-hq.gutools.co.uk`
- The TLS certificate for `public.security-hq.gutools.co.uk`
- The CNAME for `public.security-hq.gutools.co.uk`

Remove `public.security-hq.gutools.co.uk` CNAME

---

cdk/lib/__snapshots__/security-hq.test.ts.snap
cdk/lib/security-hq.ts

Removes the redirect from `public.security-hq.gutools.co.uk` to `security-hq.gutools.co.uk`.
This was missed in #813.

Remove 301 redirect

---

.github/workflows/ci-sbt.yml
cdk/jest.setup.js
cdk/package.json
cdk/yarn.lock

Since #775 `@guardian/private-infrastructure-config` is no longer used, so can be removed.
- Fewer dependencies
- A simpler build

chore(deps): Remove unused dependency `@guardian/private-infrastructure-config`

---

.github/workflows/ci-sbt.yml
build.sbt
hq/conf/riff-raff.yaml
project/plugins.sbt
script/ci

In this change we remove the [sbt-riffraff-artifact plugin](https://github.com/guardian/sbt-riffraff-artifact) in favour of [guardian/action-riff-raff](https://github.com/guardian/actions-riff-raff) making the application code ignorant of Riff-Raff (i.e. simpler).
Fewer application dependencies to keep up to date.
- Find the build in Riff-Raff
- Compare the files available between [this branch](https://riffraff.gutools.co.uk/deployment/request/deployFiles?projectName=security-hq&id=2290) and [main](https://riffraff.gutools.co.uk/deployment/request/deployFiles?projectName=security-hq&id=2287) (see comments for reasoning):
- The `.deb` file should match
- The CFN template should differ
- Deploy and Security-HQ should still work ([I've done this with …

ci: Switch to `guardian/actions-riff-raff`

---

hq/conf/riff-raff.yaml

Move to use https://amigo.gutools.co.uk/recipes/arm64-jammy-java11-security.
This will allow us to:
- Move Security-HQ to 22.04 to avoid the 18.04 EOL
Deploy this PR to the PROD environment and check the EC2 instances with the new AMI are successfully brought into service & that we can access the Security-HQ.
See: https://riffraff.gutools.co.uk/deployment/view/027c9159-462c-47c4-9767-fdfac66aa3a0?verbose=1
Can we use the jammy AMI to successfully deploy Security-HQ?
Security-HQ is not deployable with Jammy base AMIs, we'll revert.

Use arm64-jammy-java11-security as the AMI

---

build.sbt
hq/conf/riff-raff.yaml

The `allowedStages` configuration sets the entries in the drop-down in Riff-Raff, meaning the chance of deploying to an undesired stage is reduced.
We only have a PROD stage, so set `allowedStages` accordingly.
Use the [validation tool](https://riffraff.gutools.co.uk/configuration/validation) to ensure a valid config file.

chore: Configure `allowedStages` in `riff-raff.yaml`

---

build.sbt

Updates the version of [anghammarad](https://github.com/guardian/anghammarad) being used.
This helps address a vulnerability in a transitive dependency, and is an alternative to #1002.

chore(deps): Bump `anghammarad-client` from 1.2.0 to 1.7.5

---

build.sbt
lambda/security-groups/src/main/scala/com/gu/hq/Notifier.scala

The `Stack`, `Stage`, `App`, and `gu:repo` tags can be used to identify a service, and where it is defined.
Add these to the notification message to make it easier to triage at a glance.
Here's what the current chat notification looks like:

feat: Add Stack, Stage, App to notification message

---

build.sbt
lambda/security-groups/src/main/scala/com/gu/hq/Notifier.scala

Improves on https://github.com/guardian/security-hq/pull/1006, to better handle those cases where the `Stack`, `Stage`, `App`, or `gu:repo` tags are not present.
Printing all the tags offers better UX, as when the specific tags are all `unknown`, the message isn't very helpful:

fix: Display all tags on a security group 

---

build.sbt

Bump the version of [Anghammarad](https://github.com/guardian/anghammarad) used to resolve a high vulnerability reported by Snyk.

chore(deps): Bump anghammarad-client from 1.7.5 to 1.8.1

---

cdk/bin/cdk.ts
cdk/lib/__snapshots__/security-hq.test.ts.snap
cdk/lib/security-hq.test.ts
cdk/package-lock.json
cdk/package.json

Uses a [recent change to GuCDK](https://github.com/guardian/cdk/releases/tag/v52.2.0) to enable backup of the DynamoDb table.

feat: Enable backup of DynamoDb table

---

hq/app/api/Snyk.scala

Stop using deprecated endpoints.
Snyk's V1 projects API is [EOL](https://go.snyk.io/rs/677-THP-415/images/230815_External_Migration_Guide.pdf). For SHQ to continue working, we need to make this change
No
No
This has been deployed locally, and to PROD. Both environments are still able to retrieve Snyk data

Stop using v1 api

---

.github/dependabot.yml

Switch from weekly to monthly dependabot PRs
Security HQ is in maintenance mode, and we have plans to deprecate it soon. Keeping it's dependencies up to date is not as important as other projects the team maintains. Less time reviewing these PRs means more time for other priorities.
No
No
No

reduce frequency of dependency updates

---

build.sbt

Bumps logback-classic (and core) to versions that don't have high vulnerabilities. Because Play ships with a vulnerable version of logback (even Play 2.9), I have added the dependency explicitly so that it overrides Play's version.
Note: I could have updated Play to v.2.9 and sbt to v1.9.7, but it wasn't necessary to fix the vulnerabilities. Please comment if you think this should be done as part of this change too.
I don't think so. 
I don't think so.
I tested this by running `./script/ci` `sbt test` `sbt compile` and `snyk test` to ensure the high vulnerabilities had been removed.

Fix: bump logback to fix high Snyk vulnerabilities

---

lambda/security-groups/src/main/scala/com/gu/hq/Notifier.scala
lambda/security-groups/src/test/scala/com/gu/hq/NotifierTest.scala

Target tags are presented as one key value pair per line.
Easier reading
Requires stackset update, but not urgently, it can wait until next week.
No
No

Make open security group notification more readable

---

build.sbt
hq/app/config/Config.scala
hq/app/filters/HstsFilter.scala
project/build.properties
project/plugins.sbt
script/ci

- Upgrades Play to v3.0.1.
- Upgrades various other dependencies to enable this to work. 
- Bumps the version of Security HQ to 0.5.0. 
- One change to Scala config has been made to remove an import for `GoogleServiceAccount` that doesn't exist in the later version of Google Auth.
This has been done to  remove our dependence on Akka. Play v3 uses Pekko instead.
I don't think so.
I have updated the local DEV config in S3 with a longer application secret, as required by Play v3. I don't  think PROD will be affected.

chore: upgrade to Play v3

---

.github/workflows/dependency-graph.yml

We're continuing to investigate Github's dependency scanning.
As well as using Snyk, we'll now have dependency information available in Github. Having a few repos integrated (janus-app is already done) helps us look at how we'll manage this across the org.
N/A
N/A
N/A

Add workflow for sending dependency information to Github

---

project/plugins.sbt

Adds the SBT dependency tree plugin.
This will allow us to generate the dependency tree locally, including using the useful `dependencyBrowseTree` command to display a searchable tree in the browser.

chore: add dependency tree plugin

---

hq/markdown/vulnerability-management.md

Small tweaks to update documentation about dependabot/snyk
Add a section talking about when we expect vulnerabilities to be resolved
Increase departmental awareness of security obligations
No
No

Update vulnerability recommendations

---

hq/app/notifications/AnghammaradNotifications.scala

Tune the wording of the IAM credentials warning messages, Rreplacing "vulnerable" with "long-lived" for accuracy. "Vulnerable" suggests the key may have been compromised. This isn't what we're guarding against here. We're guarding against static IAM credentials not being rotated in a while.
Clearer messaging?

refactor: Reword IAM credential messaging

---

.github/workflows/ci-sbt.yml
.github/workflows/dependency-graph.yml
.github/workflows/inclusion.yaml
.github/workflows/stale.yml

This PR versions the actions by commit SHA, where applicable.
This is more secure, as per our [recommendations](https://github.com/guardian/recommendations/blob/main/github-actions.md).

refactor: use commit SHAs for action versions

---

build.sbt

We depend on both jackson-databind and jackson-module-scala, and explicitly ask for version 2.15.x to avoid vulnerabiltiies in 2.14.x (play's preferred version). The AWS SDK depends on jackson at version 2.17.x, which evicts our version (2.15.x) for jackson-databind, but not for the jackson-module-scala (which it doesn't know about). These incompatible versions throw an exception at start time, so the Play server does not start.
Bumping our override to 2.17.x resolves the incompatibility.
The server will start :-)
The risk with this change is that play does not work with jackson at v2.17.x. This was already an issue, because we were forcing 2.15.x. We'll keep an eye out.

Bump jackson explicitly to resolve incompatible version issue

---

.github/workflows/ci-sbt.yml
cdk/bin/cdk.ts
cdk/jest.setup.js
cdk/lib/__snapshots__/security-hq.test.ts.snap
cdk/lib/security-hq.test.ts
cdk/lib/security-hq.ts
cdk/package-lock.json
cdk/package.json
hq/conf/riff-raff.yaml
script/ci

Uses the new `GuEc2AppExperimental` available in [GuCDK v59.5.0](https://github.com/guardian/cdk/releases/tag/v59.5.0).
This formalises the changes of https://github.com/guardian/security-hq/pull/1154, installing the experimental pattern from an NPM release.
N/A as testing has been performed in https://github.com/guardian/security-hq/pull/1154.

feat: Perform EC2 deployments via CloudFormation

---

.github/workflows/dependency-graph.yml

- Installs sbt in the dependency submission workflow.
The workflow is currently broken because the latest Ubuntu doesn't come with sbt bundled.
This is the workflow run [before](https://github.com/guardian/security-hq/actions/runs/11209895261) and [after ](https://github.com/guardian/security-hq/actions/runs/11347765650)this change.

Explicitly install sbt in dependency submission workflow

---

hq/app/notifications/AnghammaradNotifications.scala

Since #1129 Security HQ doesn't present it's own dashboard for the IAM credentials report and it has been recreated in Grafana. Update the URL to reflect this.

fix: Update link to IAM credentials report

---

hq/app/aws/AwsAsyncHandler.scala
hq/app/logic/IamUnrecognisedUsers.scala
hq/app/utils/attempt/Failure.scala

We add a cause to unexpected AWS SDK client errors, and use this newly-populated field (if present) from the IAM credentials report refresh code.
This should give us insights into the current failures.

Improve error logging on IAM credentials report

---

hq/app/services/CacheService.scala
hq/app/utils/attempt/Failure.scala

Log messages on Failures now include a summary of the underlying cause, if present. This should improve error visibility across the board in Security HQ.
We also add additional error handling to the cache service. On every cache update we include a summary of which accounts have failures in their cache data.
This is motivated by the IAM remediation issues, and will give us more information for digging into the problem.

Improve error handling / logging

---

hq/app/aws/AWS.scala

Since the v2 SDK migration, we have been incorrectly authenticatinng the STS Assume Role Credentials Provider used by security-hq when integrating with other AWS accounts.
Instead of using the named Janus account profile (which will not exist in production), we omit the argument in order to use the default provider chain.

fix: role assumption in production

---

hq/app/aws/iam/CredentialsReport.scala

Since the AWS v2 Java SDK update, the test of whether the report has finished being generated was broken. We correct this here so that we will detect a finished report.
This will stop us getting rate limit errors, and restore IAM remediation functionality.
The v1 SDK used a String for the status field, but in v2 this is an enum called `ReportType`. We had a type error warning, but because this projefct does not have fatal warnings enabled it was easy to miss. This incorrect equality check means we will be constantly retrying the report generation check instead of proceeding to load the report.

Fixes detection of report generation after the v2 SDK update

---

hq/app/aws/iam/CredentialsReport.scala

This should be the last step on fixing the credentials report logic, following the AWS v2 Java SDK update.
I've seen the report get cached locally following this change.
This PR follows https://github.com/guardian/security-hq/pull/1194 and https://github.com/guardian/security-hq/pull/1196, following the SDK update (https://github.com/guardian/security-hq/pull/1179) some time back.

Fix a date format runtime exception

---

build.sbt
hq/app/aws/AwsAsyncHandler.scala

Remove unused code that depends on the v1 AWS SDK
This dead code was previously still compiling because the v1 AWS Java SDK was being brought in as a transitive dependency via the janus-config-tools library.
With the bump to v2 of janus-config-tools this is no longer the case, which highlighted this problem. Removing the unused code fixes the issue.
This lets us update to the latest version of the janus-config-tools library, removes unused code, and eliminates an implicit dependency on the end-of-life v1 AWS Java SDK.
Closes https://github.com/guardian/security-hq/pull/1212

Remove unused code that depends on the v1 AWS SDK

---

build.sbt

Bumps `awssdk` to latest to remediate a High severity vulnerability in `netty-handler`: https://github.com/advisories/GHSA-4g8c-wm8x-jfhw

fix: high severity vulnerability in netty-handler

---

build.sbt
hq/test/schedule/unrecognised/IamUnrecognisedUsersTest.scala

Upgrades janus-config-tools library from v2.0.0 to [v3.0.0](https://github.com/guardian/janus-app/releases/tag/v3.0.0).  
This migrates some case classes to use java.time types so there's a small change to a test.
Keeps the dependencies up to date.
There are still plenty of uses of Joda time in this repo but they will be addressed later on.

chore(deps): bump janus-config-tools to v3.0.0

---

build.sbt

This version bump adds a new feature to the config tools library, which means we need to update the library to support new config files. Otherwise, this doesn't affect how Security HQ is consuming the parsed file.
We'll continue to be able to parse the Janus config file.
See the following related PRs:
- https://github.com/guardian/janus-app/pull/539
- https://github.com/guardian/janus/pull/4697
- https://github.com/guardian/janus/pull/4698

Bump janus-config-tools

---

cdk/bin/cdk.ts
cdk/lib/__snapshots__/security-hq.test.ts.snap
cdk/lib/security-hq.test.ts
cdk/lib/security-hq.ts

This change does a small thing.
Specifically, it increases the timeout for the addition of the single instance to the stack's ASG from 3 minutes to 5 minutes.
We're seeing Cloudformation deployments failing occasionally because the instance is timing out before it's fully healthy.     
But repeating the deploy always works, which makes us think we aren't giving the instance long enough to sort itself out.
For example, in this [failed deploy](https://riffraff.gutools.co.uk/deployment/view/973e39e3-34b0-411a-af02-c520f6f1223a):
> [11:45:39] New instance(s) added to autoscaling group - Waiting on 1 resource signal(s) with a timeout of PT3M.
> [11:48:36] AutoScalingGroupSecurityhqASG8DD277A5 (AWS::AutoScaling::AutoScalingGroup): UPDATE_IN_PROGRESS
> [11:48:36] Failed to receive 1 resource …

fix: Increase resource signal timeout for ASG

---

.github/workflows/ci-sbt.yml

This should stop comments appearing in PRs linking to a non-existent Code stage, according to the [documentation](https://github.com/guardian/actions-riff-raff?tab=readme-ov-file#commentingenabled).
See [this example](https://github.com/guardian/security-hq/pull/1261#issuecomment-3206908928).

ci: Stop linking to a Code stage deployment
