hq/test/utils/attempt/AttemptValues.scala

Here's an improvement copied from another project where I used this approach (as discussed yesterday, Kate).
cc @katebee @abdusahin

Use "clue" to provide test feedback on failed attempts

---

hq/app/aws/AwsAsyncHandler.scala
hq/app/aws/iam/CredentialsReport.scala
hq/app/aws/iam/IAMClient.scala
hq/app/controllers/HQController.scala
hq/app/logic/DateUtils.scala
hq/app/logic/Retry.scala
hq/app/model/models.scala
hq/app/views/iam/iamCredReport.scala.html
hq/conf/routes
hq/test/aws/iam/CredentialsReportTest.scala
hq/test/logic/RetryTest.scala

- Retrieve credentials audit report from AWS
- Add controller/view stubs for report display

Credentials auditing

---

hq/app/aws/iam/CredentialsReport.scala
hq/app/aws/iam/IAMClient.scala
hq/app/controllers/HQController.scala
hq/app/logic/Retry.scala
hq/app/utils/attempt/Attempt.scala
hq/app/views/iam/iamCredReport.scala.html
hq/test/aws/iam/CredentialsReportTest.scala
hq/test/logic/RetryTest.scala

- Introduce delay to the Retry logic

 - Handle 'no_information' case for password last updated field

---

hq/app/aws/ec2/EC2.scala
hq/app/aws/iam/IAMClient.scala
hq/app/aws/support/TrustedAdvisor.scala
hq/app/controllers/HQController.scala
hq/app/logic/DateUtils.scala
hq/app/logic/ReportDisplay.scala
hq/app/views/fragments/statusSummary.scala.html
hq/app/views/iam/iam.scala.html
hq/app/views/iam/iamAccount.scala.html
hq/app/views/iam/iamCredReport.scala.html
hq/app/views/iam/iamCredReportBody.scala.html
hq/conf/routes
hq/test/aws/ec2/EC2Test.scala
hq/test/aws/support/TrustedAdvisorSGOpenPortsTest.scala

-Display security groups in-use
-Sort flags by alert level
-Sort flags by port priority

Security groups sorting

---

build.sbt
hq/app/AppComponents.scala
hq/app/AppLoader.scala
hq/app/auth/SecurityHQAuthActions.scala
hq/app/config/Config.scala
hq/app/controllers/AuthController.scala
hq/app/controllers/HQController.scala
hq/app/controllers/SecurityGroupsController.scala
hq/app/controllers/UtilityController.scala
hq/app/utils/attempt/PlayIntegration.scala
hq/app/views/error.scala.html
hq/app/views/iam/iam.scala.html
hq/app/views/iam/iamAccount.scala.html
hq/app/views/iam/iamCredReport.scala.html
hq/app/views/index.scala.html
hq/app/views/loginError.scala.html
hq/app/views/main.scala.html
hq/app/views/sgs/sgs.scala.html
hq/app/views/sgs/sgsAccount.scala.html
hq/conf/application.conf
hq/conf/routes
project/build.properties
project/plugins.sbt

- Play upgrade to 2.6.7
- Assets changes

Upgrade to Play 2.6.7

---

cloudformation/watched-account.template.yaml
hq/README.md
hq/app/aws/ec2/EC2.scala
hq/app/logic/SecurityGroupDisplay.scala
hq/app/model/models.scala
hq/app/views/fragments/openSecurityGroups.scala.html
hq/test/aws/ec2/EC2Test.scala
hq/test/logic/SecurityGroupDisplayTest.scala

- Pull name of the VPC linked to the security group
- Open resources in new tab.

Pull VPC details of the Security Groups

---

hq/app/aws/ec2/EC2.scala
hq/app/model/models.scala
hq/app/utils/attempt/Attempt.scala
hq/app/views/fragments/openSecurityGroups.scala.html
hq/test/aws/ec2/EC2Test.scala
hq/test/aws/support/TrustedAdvisorSGOpenPortsTest.scala
hq/test/utils/attempt/AttemptTest.scala

Display Cloudformation  stack id & name on security groups page.

Display Cloudformation  stack id & name

---

hq/app/aws/ec2/EC2.scala
hq/app/model/models.scala
hq/app/utils/attempt/Attempt.scala
hq/app/views/fragments/openSecurityGroups.scala.html
hq/test/aws/ec2/EC2Test.scala
hq/test/aws/support/TrustedAdvisorSGOpenPortsTest.scala
hq/test/utils/attempt/AttemptTest.scala

Reverts guardian/security-hq#34
Until the Cloudformation of the StackSets is complete

Revert "Display Cloudformation stack id & name"

---

hq/app/aws/ec2/EC2.scala
hq/app/model/models.scala
hq/app/utils/attempt/Attempt.scala
hq/app/views/fragments/openSecurityGroups.scala.html
hq/test/aws/ec2/EC2Test.scala
hq/test/aws/support/TrustedAdvisorSGOpenPortsTest.scala
hq/test/utils/attempt/AttemptTest.scala

Reverts guardian/security-hq#47

Revert "Revert "Display Cloudformation stack id & name""

---

hq/README.md

The numbering is now correct on my .md reader.

README small update

---

hq/README.md

This corrects the item numbering of that section. Without this the 7th section will appear as "1".

Readme correction to correct numbering

---

cloudformation/security-hq.template.yaml

Correct expression for cloudformation permissions.
Deploy will work!
Yes.
No

Fix cloudformation tag permissions

---

cloudformation/security-hq.template.yaml

Reverts guardian/security-hq#67

Revert "Fix cloudformation tag permissions"

---

hq/markdown/snyk.md

Improvements to Snyk documentation based on Kate's feedback.
Help people to use Snyk.
No.

Feedback on snyk instructions

---

cloudformation/security-hq.template.yaml
hq/upstart/security-hq.conf

Improves the decision for how much memory to allocate
ie don't use so much on small instances that the app + kernel > 100%
Yes - it switches to instance type small from tiny.
No.

Better memory management on small instances

---

build.sbt
hq/app/AppComponents.scala
hq/app/auth/SecurityHQAuthActions.scala
hq/app/config/Config.scala
hq/app/controllers/AuthController.scala
hq/app/controllers/HQController.scala
hq/app/controllers/SecurityGroupsController.scala
hq/app/controllers/SnykController.scala

Upversions Play GoogleAuth library, and implements call to new method for setting up google auth.
Should finally kill the anti-forgery token problem.
No.
No.

Upversion play-googleauth

---

hq/markdown/snyk.md

Bring Snyk documentation up to date with most recent information.
To give guidance to teams - all this info should be accessible and suitable for teams to implement.
No

Update Snyk documentation

---

hq/markdown/snyk.md
package.json

Updates the scripting to invoke snyk
Ensuring testing only runs on master, clarifying how it works, documenting.
No

Reconsider snyk scripting

---

hq/app/logic/InspectorResults.scala
hq/app/views/fragments/inspectorResult.scala.html

Adds 'completed at' field to Inspector cards.
Users can see how up to date the scan is
No
No

Add completed-at to Inspector cards

---

build.sbt
cloudformation/watched-account.template.yaml

Builds a versioned jar.
Deploys from the versioned jar in S3.
Stacksetted lambdas need to be updated from versioned lambdas for ease of use.
Yes
No

Update cloudformation for watched accounts

---

cloudformation/watched-account.template.yaml

Here we add EFS permissions in order to implement PR https://github.com/guardian/security-hq/pull/179.

Adds EFS permissions to Stackset

---

cloudformation/watched-account.template.yaml

Required for PR https://github.com/guardian/security-hq/pull/181.

Adds additional required EFS permission

---

hq/markdown/vulnerability-management.md

Puts the vulnerabilities document into rough priority order, adds ❗ warnings about not getting bogged down in low severity issues.

Reorder docs into rough priority order, add priority guidance.

---

hq/markdown/vulnerability-management.md

Adds a section identifying critical vulnerabilities agreed on earlier today to the vulnerabilities docs

Add 'critical vulnerabilities' section

---

hq/app/config/Config.scala
hq/markdown/vulnerability-management.md

...and remind people that they should have some kind of vulnerability scanner installed on PROD applications

Add vulnerability docs link to index page

---

hq/markdown/vulnerability-management.md

Add recommended credential age

---

hq/markdown/vulnerability-management.md

Add link to GCP section of security HQ in vulnerability docs

---

hq/app/schedule/CredentialsReportJob.scala

This PR refactors the run function in order to make it testable.

Make credentials notification run function testable

---

hq/markdown/wazuh.md

Removes ARN from Wazuh guidance doc re: @katebee's advice. Thanks, @katebee! 
Removes account numbers from the repo, which is best avoided.
@katebee, do we need to scrub any repo history here?

Remove ARN from Wazuh guidance doc

---

hq/app/AppComponents.scala
hq/app/aws/AWS.scala
hq/app/model/models.scala
hq/app/schedule/CredentialsMessages.scala
hq/app/schedule/CredentialsNotifier.scala
hq/app/schedule/CredentialsReportJob.scala

This PR adds the text of the message to be sent when permanent credentials are old or multi-factor authentication is missing.
There are a number of TODOs left in the code, which will be addressed imminently.

Adds credentials notification message

---

hq/app/views/gcp/gcp.scala.html

Corrects the GCP title to be consistent with other pages.

Fixes inconsistent GCP title

---

cloudformation/security-hq.template.yaml
hq/app/AppComponents.scala
hq/app/AppLoader.scala
hq/app/config/Config.scala
hq/app/schedule/CronSchedules.scala
hq/app/schedule/IamJob.scala
hq/app/schedule/IamMessages.scala
hq/app/schedule/IamNotifier.scala
hq/conf/application.conf
hq/test/schedule/IamAuditTest.scala

This PR adds the final changes required to set up the IAM notifier, which sends emails to AWS accounts notifying them of their old permanent credentials which need rotating or their credentials missing multi-factor authentication.
The emails will be sent on the first Monday of every month. The hope is that at the end of the month we automatically disable credentials posing a security risk. This will be a forthcoming piece of work.
This new feature automates the process of checking for old permanent AWS credentials or those missing mfa, so that developers are no longer required to manually check for this. It also paves the way for the automatic disablement of these credentials, which will greatly improve the Guardian's security stance. 
Furthermore, this work has added a reusable …

Add final quartz components for IAM notifier

---

hq/app/services/MetricService.scala

Discards 'suppressed' security group findings from  cloudwatch metrics
Security HQ reads security group data from trusted advisor, which flags up any security groups with ports open to the world other than 443 and 80. In some circumstances these ports need to be open. In this scenario developers can go into trusted advisor and manually exclude the security groups from the scan. 
If  this has  been done, we should assume that  it was done for  a good reason and not flag the security group up in our metrics as problematic. 
No

Discard suppressed security groups from cloudwatch metrics

---

cloudformation/watched-account.template.yaml

add permission ListAccessKeys

---

cloudformation/watched-account.template.yaml

add permission iam-ListMFADevices

---

hq/app/schedule/CronSchedules.scala
hq/app/schedule/IamJob.scala

Reverts guardian/security-hq#261 as we need to fix some issues with the emails going out

Revert "Change IAM job CRON schedule to daily"

---

hq/conf/application.conf

Remove unused config value

---

README.md

While setting up the project I noticed a small correction to the dev-nginx commands you need to run on initial set up.

Correct dev-nginx instructions

---

hq/app/schedule/IamFlaggedUsers.scala

Improves this log line message, so that it makes debugging of this feature easier in the future.

Improve log line message

---

hq/app/schedule/CronSchedules.scala

I made a mistake, so trying this again. Third time lucky 😂

Turn the IAM job on (again)

---

build.sbt
hq/app/AppComponents.scala
hq/app/schedule/IamMessages.scala
hq/app/schedule/unrecognised/IamUnrecognisedUserJob.scala
hq/app/schedule/unrecognised/IamUnrecognisedUsers.scala
hq/app/schedule/vulnerable/IamDisableAccessKeys.scala
hq/app/schedule/vulnerable/IamVulnerableUserJob.scala
hq/test/schedule/IamUnrecognisedUserTest.scala

This adds password removal and access key disablement to the new unrecognised users job. It also sends a disablement email notification. 
Fleshes out more of the functionality of the job before we hook it up to real data and do some end to end testing.
No
No

Disable keys and logins in unrecognised users job

---

cdk/lib/__snapshots__/security-hq.test.ts.snap
cdk/lib/security-hq.ts
cdk/package.json
cdk/yarn.lock

Addition to https://github.com/guardian/security-hq/pull/329 to add DNS record.
We can then repoint the DNS in code without having to do (risky) manual NS1 changes.

Take over DNS

---

hq/app/logic/IamRemediation.scala
hq/test/logic/IamRemediationTest.scala

Adds tests and implementation for `iam-remediation-identifyAllUsersWithOutdatedCredentials`.

Iam remediation - identify all users with outdated credentials

---

cloudformation/security-hq.template.yaml
hq/conf/riff-raff.yaml

Improves on the hacky solution in:
https://github.com/guardian/security-hq/pull/337

Support dual stacks in RR

---

hq/app/schedule/unrecognised/IamUnrecognisedUserJob.scala
hq/app/schedule/vulnerable/IamDisableAccessKeys.scala

This PR fixes two bugs.
First, a notification will only be sent if one of the access keys of the unrecognised user was enabled or the user had a password. If either of these conditions are true, SHQ has a reason to notify the aws account.
Second, SHQ no longer attempts to disable a key which is already disabled.
These fixes mean that a notification will not be sent if no action has been taken by SHQ. Second, SHQ will not make unnecessary requests to disable an access key.
No.
No.
No.

More unrecognised user bug fixes

---

cdk/lib/__snapshots__/security-hq.test.ts.snap
cdk/lib/security-hq.ts

PR #378 failed with a CFN error that the db table name needs to be changed so doing that now.
Outlined in PR #378.
Yes.
No.
No.

Changing the DB name, so CFN update works

---

hq/app/aws/AWS.scala

This updates nearly all of our AWS SDK clients to use a _cached_ rather than _fixed_ thread pool. Why is that desirable? We spotted that the application was falling over after approximately 24 hours. We eventually tracked this down to an OutOfMemoryException triggered by a lack of available threads. 
After much examination of the threading behaviour, we believe this happens because we are using the default `FixedThreadPool` that AWS provides in each of our clients, which has a maximum size of 10, and does not terminate idle threads whatsoever. Due to the behaviour of our application (large batches of network requests on a predictable schedule) we were observing that the thread pools slowly filled up over time and were never emptied of idle threads. Some of these threads were re-used, but …

Use cached thread pool for most AWS client operations

---

build.sbt
project/plugins.sbt

Updates to the latest Play version, motivated mainly by the fixing of an annoying issue where you can't cancel execution of `run`. https://github.com/playframework/playframework/issues/11032

Upgrade to Play 2.8.13

---

project/build.properties

Bumps to 1.6.2 of sbt, the latest version.

Update to sbt 1.6.2

---

hq/app/notifications/AnghammaradNotifications.scala

We're currently only using the account as a target for notifications in the IAM remediation jobs. This PR adds stack, stage, app as targets if they exist as tags on the IAM user.
Accounts that are shared by multiple teams can tag their IAM Users and set up an appropriate anghammarad mapping to get better targeted notifications.
No
Not totally necessary but we may review the mappings in conjunction with this change.
No

Use IAM User tags to determine anghammarad targets in remediation jobs

---

.github/workflows/snyk-pr.yml

Turns out it doesn't default to the default branch!

Snyk PR check fix

---

hq/app/notifications/AnghammaradNotifications.scala

This changes the email subject line to make it a bit more readable and explicit. I'm afraid the current subject doesn't make it clear that an action is needed and the email will be ignored.

Minor tweaks to emails sent by creds reaper

---

hq/markdown/snyk.md

This information is available at the linked docs, and what is referenced here is out of date.
Simplify the docs, not have to update in multiple places when there are changes.
See: https://github.com/guardian/.github/pull/22

Remove duplicate Snyk setup docs

---

.github/workflows/snyk.yml

Removes a comment that is no longer correct

Remove incorrect comment

---

hq/markdown/snyk.md

Updates instructions for accessing snyk
Simplifies the process, and removes the need for a special link that needs to be kept secret
no

simplify login instructions. no special link required

---

hq/app/aws/iam/CredentialsReport.scala

This will be helpful to understand who has emergency access to our accounts.
Although SHQ has a web UI for this information, it is inaccessible when the VPN is unavailable. When the VPN is unavailable is when we want this information. Awkward!

chore: Log IAM users in an account

---

hq/app/aws/iam/CredentialsReport.scala

Extends the changes in #746 adding logging markers to make it easier to query in Kibana.

chore: Add more detail to IAM user log line

---

README.md
hq/app/views/s3/publicBuckets.scala.html
hq/app/views/s3/publicBucketsAccount.scala.html
hq/app/views/sgs/sgs.scala.html
hq/app/views/sgs/sgsAccount.scala.html
hq/markdown/vulnerability-management.md
script/debug

Update doc to make clear the information displayed is only as up to date as the last run for AWS Trusted Advisor. Also put links in README to other doc available in repo, because that would have made my life easier. Some info about how to debug added too.

Update doc to make clear where the gathered information comes from

---

.alexrc.js
.github/CONTRIBUTING.md
.github/workflows/inclusion.yaml
README.md
hq/markdown/guardduty-sechub-common-problems.md
hq/markdown/snyk.md
hq/markdown/vulnerability-management.md
hq/markdown/wazuh.md

A continuation of the work on the [recommendations repo](https://github.com/guardian/recommendations/pull/156), this PR introduces Alex linting to Security HQ documentation
Inclusion is good! Assuming one's skillset is universal is less good!
No
No

add inclusion linting

---

build.sbt

This fixes an issue with the `locale` field in Google's response during the login process. See https://github.com/guardian/play-googleauth/pull/218.
`play-secret-rotation` is also updated to v7.1.0 due to binary compatibility.
More reliable login experience.

chore(deps): Update `play-googleauth` to v4.0.0

---

cdk/lib/__snapshots__/security-hq.test.ts.snap
cdk/package-lock.json
cdk/package.json

- Bumps GuCDK to latest and its peer deps.
- Updates the snapshot.

chore(deps): bump GuCDK
